// Explicitly re-export generated contract utilities with named exports
export {
  // Generated actions: contract artifacts
  lilNounsAuctionAbi, // LilNounsAuction ABI
  lilNounsAuctionAddress, // LilNounsAuction addresses
  lilNounsAuctionConfig, // LilNounsAuction config
  lilNounsDataAbi, // LilNounsData ABI
  lilNounsDataAddress, // LilNounsData addresses
  lilNounsDataConfig, // LilNounsData config
  lilNounsDescriptorAbi, // LilNounsDescriptor ABI
  lilNounsDescriptorAddress, // LilNounsDescriptor addresses
  lilNounsDescriptorConfig, // LilNounsDescriptor config
  lilNounsEnsMapperAbi, // LilNounsEnsMapper ABI
  lilNounsEnsMapperAddress, // LilNounsEnsMapper addresses
  lilNounsEnsMapperConfig, // LilNounsEnsMapper config
  lilNounsGovernorAbi, // LilNounsGovernor ABI
  lilNounsGovernorAddress, // LilNounsGovernor addresses
  lilNounsGovernorConfig, // LilNounsGovernor config
  lilNounsTokenAbi, // LilNounsToken ABI
  lilNounsTokenAddress, // LilNounsToken addresses
  lilNounsTokenConfig, // LilNounsToken config
  lilNounsTreasuryAbi, // LilNounsTreasury ABI
  lilNounsTreasuryAddress, // LilNounsTreasury addresses
  lilNounsTreasuryConfig, // LilNounsTreasury config
  // Generated actions: read helpers
  readLilNounsAuction, // Actions read helper for LilNounsAuction
  readLilNounsAuctionFetchNextNoun, // Actions read helper for LilNounsAuction.fetchNextNoun
  readLilNounsAuctionFetchNoun, // Actions read helper for LilNounsAuction.fetchNoun
  readLilNounsAuctionGetCurrentVrgdaPrice, // Actions read helper for LilNounsAuction.getCurrentVrgdaPrice
  readLilNounsAuctionGetSeederBlockNumber, // Actions read helper for LilNounsAuction.getSeederBlockNumber
  readLilNounsAuctionGetTargetSaleTime, // Actions read helper for LilNounsAuction.getTargetSaleTime
  readLilNounsAuctionGetVrgdaPrice, // Actions read helper for LilNounsAuction.getVrgdaPrice
  readLilNounsAuctionLilNounderRewardNouns, // Actions read helper for LilNounsAuction.lilNounderRewardNouns
  readLilNounsAuctionNextNounId, // Actions read helper for LilNounsAuction.nextNounId
  readLilNounsAuctionNextNounIdForCaller, // Actions read helper for LilNounsAuction.nextNounIdForCaller
  readLilNounsAuctionNounsDaoRewardNouns, // Actions read helper for LilNounsAuction.nounsDaoRewardNouns
  readLilNounsAuctionNounsDescriptor, // Actions read helper for LilNounsAuction.nounsDescriptor
  readLilNounsAuctionNounsSeeder, // Actions read helper for LilNounsAuction.nounsSeeder
  readLilNounsAuctionNounsSoldAtAuction, // Actions read helper for LilNounsAuction.nounsSoldAtAuction
  readLilNounsAuctionNounsToken, // Actions read helper for LilNounsAuction.nounsToken
  readLilNounsAuctionOwner, // Actions read helper for LilNounsAuction.owner
  readLilNounsAuctionPaused, // Actions read helper for LilNounsAuction.paused
  readLilNounsAuctionPoolSize, // Actions read helper for LilNounsAuction.poolSize
  readLilNounsAuctionProxiableUuid, // Actions read helper for LilNounsAuction.proxiableUuid
  readLilNounsAuctionReservePrice, // Actions read helper for LilNounsAuction.reservePrice
  readLilNounsAuctionSeederBlockNumber, // Actions read helper for LilNounsAuction.seederBlockNumber
  readLilNounsAuctionStartTime, // Actions read helper for LilNounsAuction.startTime
  readLilNounsAuctionTargetPrice, // Actions read helper for LilNounsAuction.targetPrice
  readLilNounsAuctionUpdateInterval, // Actions read helper for LilNounsAuction.updateInterval
  readLilNounsAuctionUsedBlockNumbers, // Actions read helper for LilNounsAuction.usedBlockNumbers
  readLilNounsAuctionWethAddress, // Actions read helper for LilNounsAuction.wethAddress
  readLilNounsData, // Actions read helper for LilNounsData
  readLilNounsDataCreateCandidateCost, // Actions read helper for LilNounsData.createCandidateCost
  readLilNounsDataFeeRecipient, // Actions read helper for LilNounsData.feeRecipient
  readLilNounsDataMaxProposalCalls, // Actions read helper for LilNounsData.maxProposalCalls
  readLilNounsDataOwner, // Actions read helper for LilNounsData.owner
  readLilNounsDataPendingOwner, // Actions read helper for LilNounsData.pendingOwner
  readLilNounsDataPriorVotesBlocksAgo, // Actions read helper for LilNounsData.priorVotesBlocksAgo
  readLilNounsDataPropCandidates, // Actions read helper for LilNounsData.propCandidates
  readLilNounsDataProxiableUuid, // Actions read helper for LilNounsData.proxiableUuid
  readLilNounsDataToken, // Actions read helper for LilNounsData.token
  readLilNounsDataUpdateCandidateCost, // Actions read helper for LilNounsData.updateCandidateCost
  readLilNounsDataUpgradeInterfaceVersion, // Actions read helper for LilNounsData.upgradeInterfaceVersion
  readLilNounsDescriptor, // Actions read helper for LilNounsDescriptor
  readLilNounsDescriptorAccessories, // Actions read helper for LilNounsDescriptor.accessories
  readLilNounsDescriptorAccessoryCount, // Actions read helper for LilNounsDescriptor.accessoryCount
  readLilNounsDescriptorArePartsLocked, // Actions read helper for LilNounsDescriptor.arePartsLocked
  readLilNounsDescriptorArt, // Actions read helper for LilNounsDescriptor.art
  readLilNounsDescriptorBackgroundCount, // Actions read helper for LilNounsDescriptor.backgroundCount
  readLilNounsDescriptorBackgrounds, // Actions read helper for LilNounsDescriptor.backgrounds
  readLilNounsDescriptorBaseUri, // Actions read helper for LilNounsDescriptor.baseUri
  readLilNounsDescriptorBodies, // Actions read helper for LilNounsDescriptor.bodies
  readLilNounsDescriptorBodyCount, // Actions read helper for LilNounsDescriptor.bodyCount
  readLilNounsDescriptorDataUri, // Actions read helper for LilNounsDescriptor.dataUri
  readLilNounsDescriptorGenerateSvgImage, // Actions read helper for LilNounsDescriptor.generateSvgImage
  readLilNounsDescriptorGenericDataUri, // Actions read helper for LilNounsDescriptor.genericDataUri
  readLilNounsDescriptorGetPartsForSeed, // Actions read helper for LilNounsDescriptor.getPartsForSeed
  readLilNounsDescriptorGlasses, // Actions read helper for LilNounsDescriptor.glasses
  readLilNounsDescriptorGlassesCount, // Actions read helper for LilNounsDescriptor.glassesCount
  readLilNounsDescriptorHeadCount, // Actions read helper for LilNounsDescriptor.headCount
  readLilNounsDescriptorHeads, // Actions read helper for LilNounsDescriptor.heads
  readLilNounsDescriptorIsDataUriEnabled, // Actions read helper for LilNounsDescriptor.isDataUriEnabled
  readLilNounsDescriptorOwner, // Actions read helper for LilNounsDescriptor.owner
  readLilNounsDescriptorPalettes, // Actions read helper for LilNounsDescriptor.palettes
  readLilNounsDescriptorRenderer, // Actions read helper for LilNounsDescriptor.renderer
  readLilNounsDescriptorTokenUri, // Actions read helper for LilNounsDescriptor.tokenUri
  readLilNounsEnsMapper, // Actions read helper for LilNounsEnsMapper
  readLilNounsEnsMapperAddr, // Actions read helper for LilNounsEnsMapper.addr
  readLilNounsEnsMapperEns, // Actions read helper for LilNounsEnsMapper.ens
  readLilNounsEnsMapperEnsNameOf, // Actions read helper for LilNounsEnsMapper.ensNameOf
  readLilNounsEnsMapperEnsNodeOf, // Actions read helper for LilNounsEnsMapper.ensNodeOf
  readLilNounsEnsMapperIsLegacyNode, // Actions read helper for LilNounsEnsMapper.isLegacyNode
  readLilNounsEnsMapperLegacy, // Actions read helper for LilNounsEnsMapper.legacy
  readLilNounsEnsMapperName, // Actions read helper for LilNounsEnsMapper.name
  readLilNounsEnsMapperNft, // Actions read helper for LilNounsEnsMapper.nft
  readLilNounsEnsMapperOwner, // Actions read helper for LilNounsEnsMapper.owner
  readLilNounsEnsMapperProxiableUuid, // Actions read helper for LilNounsEnsMapper.proxiableUuid
  readLilNounsEnsMapperRootLabel, // Actions read helper for LilNounsEnsMapper.rootLabel
  readLilNounsEnsMapperRootNode, // Actions read helper for LilNounsEnsMapper.rootNode
  readLilNounsEnsMapperSupportsInterface, // Actions read helper for LilNounsEnsMapper.supportsInterface
  readLilNounsEnsMapperText, // Actions read helper for LilNounsEnsMapper.text
  readLilNounsEnsMapperUpgradeInterfaceVersion, // Actions read helper for LilNounsEnsMapper.upgradeInterfaceVersion
  readLilNounsGovernor, // Actions read helper for LilNounsGovernor
  readLilNounsGovernorAdmin, // Actions read helper for LilNounsGovernor.admin
  readLilNounsGovernorBallotTypehash, // Actions read helper for LilNounsGovernor.ballotTypehash
  readLilNounsGovernorDomainTypehash, // Actions read helper for LilNounsGovernor.domainTypehash
  readLilNounsGovernorDynamicQuorumVotes, // Actions read helper for LilNounsGovernor.dynamicQuorumVotes
  readLilNounsGovernorGetActions, // Actions read helper for LilNounsGovernor.getActions
  readLilNounsGovernorGetDynamicQuorumParamsAt, // Actions read helper for LilNounsGovernor.getDynamicQuorumParamsAt
  readLilNounsGovernorGetReceipt, // Actions read helper for LilNounsGovernor.getReceipt
  readLilNounsGovernorImplementation, // Actions read helper for LilNounsGovernor.implementation
  readLilNounsGovernorLatestProposalIds, // Actions read helper for LilNounsGovernor.latestProposalIds
  readLilNounsGovernorMaxProposalThresholdBps, // Actions read helper for LilNounsGovernor.maxProposalThresholdBps
  readLilNounsGovernorMaxQuorumVotes, // Actions read helper for LilNounsGovernor.maxQuorumVotes
  readLilNounsGovernorMaxQuorumVotesBps, // Actions read helper for LilNounsGovernor.maxQuorumVotesBps
  readLilNounsGovernorMaxQuorumVotesBpsUpperBound, // Actions read helper for LilNounsGovernor.maxQuorumVotesBpsUpperBound
  readLilNounsGovernorMaxRefundBaseFee, // Actions read helper for LilNounsGovernor.maxRefundBaseFee
  readLilNounsGovernorMaxRefundGasUsed, // Actions read helper for LilNounsGovernor.maxRefundGasUsed
  readLilNounsGovernorMaxRefundPriorityFee, // Actions read helper for LilNounsGovernor.maxRefundPriorityFee
  readLilNounsGovernorMaxVotingDelay, // Actions read helper for LilNounsGovernor.maxVotingDelay
  readLilNounsGovernorMaxVotingPeriod, // Actions read helper for LilNounsGovernor.maxVotingPeriod
  readLilNounsGovernorMinProposalThresholdBps, // Actions read helper for LilNounsGovernor.minProposalThresholdBps
  readLilNounsGovernorMinQuorumVotes, // Actions read helper for LilNounsGovernor.minQuorumVotes
  readLilNounsGovernorMinQuorumVotesBpsLowerBound, // Actions read helper for LilNounsGovernor.minQuorumVotesBpsLowerBound
  readLilNounsGovernorMinQuorumVotesBpsUpperBound, // Actions read helper for LilNounsGovernor.minQuorumVotesBpsUpperBound
  readLilNounsGovernorMinVotingDelay, // Actions read helper for LilNounsGovernor.minVotingDelay
  readLilNounsGovernorMinVotingPeriod, // Actions read helper for LilNounsGovernor.minVotingPeriod
  readLilNounsGovernorName, // Actions read helper for LilNounsGovernor.name
  readLilNounsGovernorNouns, // Actions read helper for LilNounsGovernor.nouns
  readLilNounsGovernorPendingAdmin, // Actions read helper for LilNounsGovernor.pendingAdmin
  readLilNounsGovernorPendingVetoer, // Actions read helper for LilNounsGovernor.pendingVetoer
  readLilNounsGovernorProposalCount, // Actions read helper for LilNounsGovernor.proposalCount
  readLilNounsGovernorProposalMaxOperations, // Actions read helper for LilNounsGovernor.proposalMaxOperations
  readLilNounsGovernorProposals, // Actions read helper for LilNounsGovernor.proposals
  readLilNounsGovernorProposalThreshold, // Actions read helper for LilNounsGovernor.proposalThreshold
  readLilNounsGovernorProposalThresholdBps, // Actions read helper for LilNounsGovernor.proposalThresholdBps
  readLilNounsGovernorQuorumParamsCheckpoints, // Actions read helper for LilNounsGovernor.quorumParamsCheckpoints
  readLilNounsGovernorQuorumVotes, // Actions read helper for LilNounsGovernor.quorumVotes
  readLilNounsGovernorQuorumVotesBps, // Actions read helper for LilNounsGovernor.quorumVotesBps
  readLilNounsGovernorRefundBaseGas, // Actions read helper for LilNounsGovernor.refundBaseGas
  readLilNounsGovernorState, // Actions read helper for LilNounsGovernor.state
  readLilNounsGovernorTimelock, // Actions read helper for LilNounsGovernor.timelock
  readLilNounsGovernorVetoer, // Actions read helper for LilNounsGovernor.vetoer
  readLilNounsGovernorVotingDelay, // Actions read helper for LilNounsGovernor.votingDelay
  readLilNounsGovernorVotingPeriod, // Actions read helper for LilNounsGovernor.votingPeriod
  readLilNounsToken, // Actions read helper for LilNounsToken
  readLilNounsTokenBalanceOf, // Actions read helper for LilNounsToken.balanceOf
  readLilNounsTokenCheckpoints, // Actions read helper for LilNounsToken.checkpoints
  readLilNounsTokenContractUri, // Actions read helper for LilNounsToken.contractUri
  readLilNounsTokenDataUri, // Actions read helper for LilNounsToken.dataUri
  readLilNounsTokenDecimals, // Actions read helper for LilNounsToken.decimals
  readLilNounsTokenDelegates, // Actions read helper for LilNounsToken.delegates
  readLilNounsTokenDelegationTypehash, // Actions read helper for LilNounsToken.delegationTypehash
  readLilNounsTokenDescriptor, // Actions read helper for LilNounsToken.descriptor
  readLilNounsTokenDomainTypehash, // Actions read helper for LilNounsToken.domainTypehash
  readLilNounsTokenGetApproved, // Actions read helper for LilNounsToken.getApproved
  readLilNounsTokenGetCurrentVotes, // Actions read helper for LilNounsToken.getCurrentVotes
  readLilNounsTokenGetPriorVotes, // Actions read helper for LilNounsToken.getPriorVotes
  readLilNounsTokenIsApprovedForAll, // Actions read helper for LilNounsToken.isApprovedForAll
  readLilNounsTokenIsDescriptorLocked, // Actions read helper for LilNounsToken.isDescriptorLocked
  readLilNounsTokenIsMinterLocked, // Actions read helper for LilNounsToken.isMinterLocked
  readLilNounsTokenIsSeederLocked, // Actions read helper for LilNounsToken.isSeederLocked
  readLilNounsTokenLilnoundersDao, // Actions read helper for LilNounsToken.lilnoundersDao
  readLilNounsTokenMinter, // Actions read helper for LilNounsToken.minter
  readLilNounsTokenName, // Actions read helper for LilNounsToken.name
  readLilNounsTokenNonces, // Actions read helper for LilNounsToken.nonces
  readLilNounsTokenNounsDao, // Actions read helper for LilNounsToken.nounsDao
  readLilNounsTokenNumCheckpoints, // Actions read helper for LilNounsToken.numCheckpoints
  readLilNounsTokenOwner, // Actions read helper for LilNounsToken.owner
  readLilNounsTokenOwnerOf, // Actions read helper for LilNounsToken.ownerOf
  readLilNounsTokenProxyRegistry, // Actions read helper for LilNounsToken.proxyRegistry
  readLilNounsTokenSeeder, // Actions read helper for LilNounsToken.seeder
  readLilNounsTokenSeeds, // Actions read helper for LilNounsToken.seeds
  readLilNounsTokenSupportsInterface, // Actions read helper for LilNounsToken.supportsInterface
  readLilNounsTokenSymbol, // Actions read helper for LilNounsToken.symbol
  readLilNounsTokenTokenByIndex, // Actions read helper for LilNounsToken.tokenByIndex
  readLilNounsTokenTokenOfOwnerByIndex, // Actions read helper for LilNounsToken.tokenOfOwnerByIndex
  readLilNounsTokenTokenUri, // Actions read helper for LilNounsToken.tokenUri
  readLilNounsTokenTotalSupply, // Actions read helper for LilNounsToken.totalSupply
  readLilNounsTokenVotesToDelegate, // Actions read helper for LilNounsToken.votesToDelegate
  readLilNounsTreasury, // Actions read helper for LilNounsTreasury
  readLilNounsTreasuryAdmin, // Actions read helper for LilNounsTreasury.admin
  readLilNounsTreasuryDelay, // Actions read helper for LilNounsTreasury.delay
  readLilNounsTreasuryGracePeriod, // Actions read helper for LilNounsTreasury.gracePeriod
  readLilNounsTreasuryMaximumDelay, // Actions read helper for LilNounsTreasury.maximumDelay
  readLilNounsTreasuryMinimumDelay, // Actions read helper for LilNounsTreasury.minimumDelay
  readLilNounsTreasuryPendingAdmin, // Actions read helper for LilNounsTreasury.pendingAdmin
  readLilNounsTreasuryQueuedTransactions, // Actions read helper for LilNounsTreasury.queuedTransactions
  // Generated actions: simulate helpers
  simulateLilNounsAuction, // Actions simulate helper for LilNounsAuction
  simulateLilNounsAuctionBuyNow, // Actions simulate helper for LilNounsAuction.buyNow
  simulateLilNounsAuctionInitialize, // Actions simulate helper for LilNounsAuction.initialize
  simulateLilNounsAuctionPause, // Actions simulate helper for LilNounsAuction.pause
  simulateLilNounsAuctionRenounceOwnership, // Actions simulate helper for LilNounsAuction.renounceOwnership
  simulateLilNounsAuctionSetNounsDescriptor, // Actions simulate helper for LilNounsAuction.setNounsDescriptor
  simulateLilNounsAuctionSetNounsSeeder, // Actions simulate helper for LilNounsAuction.setNounsSeeder
  simulateLilNounsAuctionSetPoolSize, // Actions simulate helper for LilNounsAuction.setPoolSize
  simulateLilNounsAuctionSetReservePrice, // Actions simulate helper for LilNounsAuction.setReservePrice
  simulateLilNounsAuctionSetUpdateInterval, // Actions simulate helper for LilNounsAuction.setUpdateInterval
  simulateLilNounsAuctionTransferOwnership, // Actions simulate helper for LilNounsAuction.transferOwnership
  simulateLilNounsAuctionUnpause, // Actions simulate helper for LilNounsAuction.unpause
  simulateLilNounsAuctionUpgradeTo, // Actions simulate helper for LilNounsAuction.upgradeTo
  simulateLilNounsAuctionUpgradeToAndCall, // Actions simulate helper for LilNounsAuction.upgradeToAndCall
  simulateLilNounsData, // Actions simulate helper for LilNounsData
  simulateLilNounsDataAcceptOwnership, // Actions simulate helper for LilNounsData.acceptOwnership
  simulateLilNounsDataCancelProposalCandidate, // Actions simulate helper for LilNounsData.cancelProposalCandidate
  simulateLilNounsDataCreateProposalCandidate, // Actions simulate helper for LilNounsData.createProposalCandidate
  simulateLilNounsDataInitialize, // Actions simulate helper for LilNounsData.initialize
  simulateLilNounsDataInitializeV2, // Actions simulate helper for LilNounsData.initializeV2
  simulateLilNounsDataRenounceOwnership, // Actions simulate helper for LilNounsData.renounceOwnership
  simulateLilNounsDataSendCandidateFeedback, // Actions simulate helper for LilNounsData.sendCandidateFeedback
  simulateLilNounsDataSendFeedback, // Actions simulate helper for LilNounsData.sendFeedback
  simulateLilNounsDataSetCreateCandidateCost, // Actions simulate helper for LilNounsData.setCreateCandidateCost
  simulateLilNounsDataSetFeeRecipient, // Actions simulate helper for LilNounsData.setFeeRecipient
  simulateLilNounsDataSetUpdateCandidateCost, // Actions simulate helper for LilNounsData.setUpdateCandidateCost
  simulateLilNounsDataTransferOwnership, // Actions simulate helper for LilNounsData.transferOwnership
  simulateLilNounsDataUpdateProposalCandidate, // Actions simulate helper for LilNounsData.updateProposalCandidate
  simulateLilNounsDataUpgradeToAndCall, // Actions simulate helper for LilNounsData.upgradeToAndCall
  simulateLilNounsDataWithdrawEth, // Actions simulate helper for LilNounsData.withdrawEth
  simulateLilNounsDescriptor, // Actions simulate helper for LilNounsDescriptor
  simulateLilNounsDescriptorAddAccessories, // Actions simulate helper for LilNounsDescriptor.addAccessories
  simulateLilNounsDescriptorAddAccessoriesFromPointer, // Actions simulate helper for LilNounsDescriptor.addAccessoriesFromPointer
  simulateLilNounsDescriptorAddBackground, // Actions simulate helper for LilNounsDescriptor.addBackground
  simulateLilNounsDescriptorAddBodies, // Actions simulate helper for LilNounsDescriptor.addBodies
  simulateLilNounsDescriptorAddBodiesFromPointer, // Actions simulate helper for LilNounsDescriptor.addBodiesFromPointer
  simulateLilNounsDescriptorAddGlasses, // Actions simulate helper for LilNounsDescriptor.addGlasses
  simulateLilNounsDescriptorAddGlassesFromPointer, // Actions simulate helper for LilNounsDescriptor.addGlassesFromPointer
  simulateLilNounsDescriptorAddHeads, // Actions simulate helper for LilNounsDescriptor.addHeads
  simulateLilNounsDescriptorAddHeadsFromPointer, // Actions simulate helper for LilNounsDescriptor.addHeadsFromPointer
  simulateLilNounsDescriptorAddManyBackgrounds, // Actions simulate helper for LilNounsDescriptor.addManyBackgrounds
  simulateLilNounsDescriptorLockParts, // Actions simulate helper for LilNounsDescriptor.lockParts
  simulateLilNounsDescriptorRenounceOwnership, // Actions simulate helper for LilNounsDescriptor.renounceOwnership
  simulateLilNounsDescriptorSetArt, // Actions simulate helper for LilNounsDescriptor.setArt
  simulateLilNounsDescriptorSetArtDescriptor, // Actions simulate helper for LilNounsDescriptor.setArtDescriptor
  simulateLilNounsDescriptorSetArtInflator, // Actions simulate helper for LilNounsDescriptor.setArtInflator
  simulateLilNounsDescriptorSetBaseUri, // Actions simulate helper for LilNounsDescriptor.setBaseUri
  simulateLilNounsDescriptorSetPalette, // Actions simulate helper for LilNounsDescriptor.setPalette
  simulateLilNounsDescriptorSetPalettePointer, // Actions simulate helper for LilNounsDescriptor.setPalettePointer
  simulateLilNounsDescriptorSetRenderer, // Actions simulate helper for LilNounsDescriptor.setRenderer
  simulateLilNounsDescriptorToggleDataUriEnabled, // Actions simulate helper for LilNounsDescriptor.toggleDataUriEnabled
  simulateLilNounsDescriptorTransferOwnership, // Actions simulate helper for LilNounsDescriptor.transferOwnership
  simulateLilNounsEnsMapper, // Actions simulate helper for LilNounsEnsMapper
  simulateLilNounsEnsMapperClaimSubname, // Actions simulate helper for LilNounsEnsMapper.claimSubname
  simulateLilNounsEnsMapperEmitAddrEvents, // Actions simulate helper for LilNounsEnsMapper.emitAddrEvents
  simulateLilNounsEnsMapperEmitTextEvents, // Actions simulate helper for LilNounsEnsMapper.emitTextEvents
  simulateLilNounsEnsMapperInitialize, // Actions simulate helper for LilNounsEnsMapper.initialize
  simulateLilNounsEnsMapperMigrateLegacySubname, // Actions simulate helper for LilNounsEnsMapper.migrateLegacySubname
  simulateLilNounsEnsMapperReleaseLegacySubname, // Actions simulate helper for LilNounsEnsMapper.releaseLegacySubname
  simulateLilNounsEnsMapperRelinquishSubname, // Actions simulate helper for LilNounsEnsMapper.relinquishSubname
  simulateLilNounsEnsMapperRenounceOwnership, // Actions simulate helper for LilNounsEnsMapper.renounceOwnership
  simulateLilNounsEnsMapperRestoreResolver, // Actions simulate helper for LilNounsEnsMapper.restoreResolver
  simulateLilNounsEnsMapperSetText, // Actions simulate helper for LilNounsEnsMapper.setText
  simulateLilNounsEnsMapperTransferOwnership, // Actions simulate helper for LilNounsEnsMapper.transferOwnership
  simulateLilNounsEnsMapperUpgradeToAndCall, // Actions simulate helper for LilNounsEnsMapper.upgradeToAndCall
  simulateLilNounsGovernor, // Actions simulate helper for LilNounsGovernor
  simulateLilNounsGovernorAcceptAdmin, // Actions simulate helper for LilNounsGovernor.acceptAdmin
  simulateLilNounsGovernorAcceptVetoer, // Actions simulate helper for LilNounsGovernor.acceptVetoer
  simulateLilNounsGovernorBurnVetoPower, // Actions simulate helper for LilNounsGovernor.burnVetoPower
  simulateLilNounsGovernorCancel, // Actions simulate helper for LilNounsGovernor.cancel
  simulateLilNounsGovernorCastRefundableVote, // Actions simulate helper for LilNounsGovernor.castRefundableVote
  simulateLilNounsGovernorCastRefundableVoteWithReason, // Actions simulate helper for LilNounsGovernor.castRefundableVoteWithReason
  simulateLilNounsGovernorCastVote, // Actions simulate helper for LilNounsGovernor.castVote
  simulateLilNounsGovernorCastVoteBySig, // Actions simulate helper for LilNounsGovernor.castVoteBySig
  simulateLilNounsGovernorCastVoteWithReason, // Actions simulate helper for LilNounsGovernor.castVoteWithReason
  simulateLilNounsGovernorExecute, // Actions simulate helper for LilNounsGovernor.execute
  simulateLilNounsGovernorInitialize, // Actions simulate helper for LilNounsGovernor.initialize
  simulateLilNounsGovernorPropose, // Actions simulate helper for LilNounsGovernor.propose
  simulateLilNounsGovernorQueue, // Actions simulate helper for LilNounsGovernor.queue
  simulateLilNounsGovernorSetDynamicQuorumParams, // Actions simulate helper for LilNounsGovernor.setDynamicQuorumParams
  simulateLilNounsGovernorSetMaxQuorumVotesBps, // Actions simulate helper for LilNounsGovernor.setMaxQuorumVotesBps
  simulateLilNounsGovernorSetMinQuorumVotesBps, // Actions simulate helper for LilNounsGovernor.setMinQuorumVotesBps
  simulateLilNounsGovernorSetPendingAdmin, // Actions simulate helper for LilNounsGovernor.setPendingAdmin
  simulateLilNounsGovernorSetPendingVetoer, // Actions simulate helper for LilNounsGovernor.setPendingVetoer
  simulateLilNounsGovernorSetProposalThresholdBps, // Actions simulate helper for LilNounsGovernor.setProposalThresholdBps
  simulateLilNounsGovernorSetQuorumCoefficient, // Actions simulate helper for LilNounsGovernor.setQuorumCoefficient
  simulateLilNounsGovernorSetVotingDelay, // Actions simulate helper for LilNounsGovernor.setVotingDelay
  simulateLilNounsGovernorSetVotingPeriod, // Actions simulate helper for LilNounsGovernor.setVotingPeriod
  simulateLilNounsGovernorVeto, // Actions simulate helper for LilNounsGovernor.veto
  simulateLilNounsGovernorWithdraw, // Actions simulate helper for LilNounsGovernor.withdraw
  simulateLilNounsToken, // Actions simulate helper for LilNounsToken
  simulateLilNounsTokenApprove, // Actions simulate helper for LilNounsToken.approve
  simulateLilNounsTokenBurn, // Actions simulate helper for LilNounsToken.burn
  simulateLilNounsTokenDelegate, // Actions simulate helper for LilNounsToken.delegate
  simulateLilNounsTokenDelegateBySig, // Actions simulate helper for LilNounsToken.delegateBySig
  simulateLilNounsTokenLockDescriptor, // Actions simulate helper for LilNounsToken.lockDescriptor
  simulateLilNounsTokenLockMinter, // Actions simulate helper for LilNounsToken.lockMinter
  simulateLilNounsTokenLockSeeder, // Actions simulate helper for LilNounsToken.lockSeeder
  simulateLilNounsTokenMint, // Actions simulate helper for LilNounsToken.mint
  simulateLilNounsTokenRenounceOwnership, // Actions simulate helper for LilNounsToken.renounceOwnership
  simulateLilNounsTokenSafeTransferFrom, // Actions simulate helper for LilNounsToken.safeTransferFrom
  simulateLilNounsTokenSetApprovalForAll, // Actions simulate helper for LilNounsToken.setApprovalForAll
  simulateLilNounsTokenSetContractUriHash, // Actions simulate helper for LilNounsToken.setContractUriHash
  simulateLilNounsTokenSetDescriptor, // Actions simulate helper for LilNounsToken.setDescriptor
  simulateLilNounsTokenSetLilNoundersDao, // Actions simulate helper for LilNounsToken.setLilNoundersDao
  simulateLilNounsTokenSetMinter, // Actions simulate helper for LilNounsToken.setMinter
  simulateLilNounsTokenSetNounsDao, // Actions simulate helper for LilNounsToken.setNounsDao
  simulateLilNounsTokenSetSeeder, // Actions simulate helper for LilNounsToken.setSeeder
  simulateLilNounsTokenTransferFrom, // Actions simulate helper for LilNounsToken.transferFrom
  simulateLilNounsTokenTransferOwnership, // Actions simulate helper for LilNounsToken.transferOwnership
  simulateLilNounsTreasury, // Actions simulate helper for LilNounsTreasury
  simulateLilNounsTreasuryAcceptAdmin, // Actions simulate helper for LilNounsTreasury.acceptAdmin
  simulateLilNounsTreasuryCancelTransaction, // Actions simulate helper for LilNounsTreasury.cancelTransaction
  simulateLilNounsTreasuryExecuteTransaction, // Actions simulate helper for LilNounsTreasury.executeTransaction
  simulateLilNounsTreasuryQueueTransaction, // Actions simulate helper for LilNounsTreasury.queueTransaction
  simulateLilNounsTreasurySetDelay, // Actions simulate helper for LilNounsTreasury.setDelay
  simulateLilNounsTreasurySetPendingAdmin, // Actions simulate helper for LilNounsTreasury.setPendingAdmin
  watchLilNounsAuctionAuctionReservePriceUpdatedEvent, // Actions event watcher for LilNounsAuction.auctionReservePriceUpdated
  watchLilNounsAuctionAuctionSettledEvent, // Actions event watcher for LilNounsAuction.auctionSettled
  watchLilNounsAuctionAuctionUpdateIntervalUpdatedEvent, // Actions event watcher for LilNounsAuction.auctionUpdateIntervalUpdated
  watchLilNounsAuctionDescriptorUpdatedEvent, // Actions event watcher for LilNounsAuction.descriptorUpdated
  // Generated actions: event watchers
  watchLilNounsAuctionEvent, // Actions event watcher for LilNounsAuction
  watchLilNounsAuctionInitializedEvent, // Actions event watcher for LilNounsAuction.initialized
  watchLilNounsAuctionOwnershipTransferredEvent, // Actions event watcher for LilNounsAuction.ownershipTransferred
  watchLilNounsAuctionPausedEvent, // Actions event watcher for LilNounsAuction.paused
  watchLilNounsAuctionPoolSizeUpdatedEvent, // Actions event watcher for LilNounsAuction.poolSizeUpdated
  watchLilNounsAuctionSeederUpdatedEvent, // Actions event watcher for LilNounsAuction.seederUpdated
  watchLilNounsAuctionUnpausedEvent, // Actions event watcher for LilNounsAuction.unpaused
  watchLilNounsAuctionUpgradedEvent, // Actions event watcher for LilNounsAuction.upgraded
  watchLilNounsDataCandidateFeedbackSentEvent, // Actions event watcher for LilNounsData.candidateFeedbackSent
  watchLilNounsDataCreateCandidateCostSetEvent, // Actions event watcher for LilNounsData.createCandidateCostSet
  watchLilNounsDataEthWithdrawnEvent, // Actions event watcher for LilNounsData.ethWithdrawn
  watchLilNounsDataEvent, // Actions event watcher for LilNounsData
  watchLilNounsDataFeedbackSentEvent, // Actions event watcher for LilNounsData.feedbackSent
  watchLilNounsDataFeeRecipientSetEvent, // Actions event watcher for LilNounsData.feeRecipientSet
  watchLilNounsDataInitializedEvent, // Actions event watcher for LilNounsData.initialized
  watchLilNounsDataOwnershipTransferredEvent, // Actions event watcher for LilNounsData.ownershipTransferred
  watchLilNounsDataOwnershipTransferStartedEvent, // Actions event watcher for LilNounsData.ownershipTransferStarted
  watchLilNounsDataProposalCandidateCanceledEvent, // Actions event watcher for LilNounsData.proposalCandidateCanceled
  watchLilNounsDataProposalCandidateCreatedEvent, // Actions event watcher for LilNounsData.proposalCandidateCreated
  watchLilNounsDataProposalCandidateUpdatedEvent, // Actions event watcher for LilNounsData.proposalCandidateUpdated
  watchLilNounsDataUpdateCandidateCostSetEvent, // Actions event watcher for LilNounsData.updateCandidateCostSet
  watchLilNounsDataUpgradedEvent, // Actions event watcher for LilNounsData.upgraded
  watchLilNounsDescriptorArtUpdatedEvent, // Actions event watcher for LilNounsDescriptor.artUpdated
  watchLilNounsDescriptorBaseUriUpdatedEvent, // Actions event watcher for LilNounsDescriptor.baseUriUpdated
  watchLilNounsDescriptorDataUriToggledEvent, // Actions event watcher for LilNounsDescriptor.dataUriToggled
  watchLilNounsDescriptorEvent, // Actions event watcher for LilNounsDescriptor
  watchLilNounsDescriptorOwnershipTransferredEvent, // Actions event watcher for LilNounsDescriptor.ownershipTransferred
  watchLilNounsDescriptorPartsLockedEvent, // Actions event watcher for LilNounsDescriptor.partsLocked
  watchLilNounsDescriptorRendererUpdatedEvent, // Actions event watcher for LilNounsDescriptor.rendererUpdated
  watchLilNounsEnsMapperAddrChangedEvent, // Actions event watcher for LilNounsEnsMapper.addrChanged
  watchLilNounsEnsMapperEvent, // Actions event watcher for LilNounsEnsMapper
  watchLilNounsEnsMapperInitializedEvent, // Actions event watcher for LilNounsEnsMapper.initialized
  watchLilNounsEnsMapperNameChangedEvent, // Actions event watcher for LilNounsEnsMapper.nameChanged
  watchLilNounsEnsMapperOwnershipTransferredEvent, // Actions event watcher for LilNounsEnsMapper.ownershipTransferred
  watchLilNounsEnsMapperSubnameClaimedEvent, // Actions event watcher for LilNounsEnsMapper.subnameClaimed
  watchLilNounsEnsMapperTextChangedEvent, // Actions event watcher for LilNounsEnsMapper.textChanged
  watchLilNounsEnsMapperUpgradedEvent, // Actions event watcher for LilNounsEnsMapper.upgraded
  watchLilNounsGovernorEvent, // Actions event watcher for LilNounsGovernor
  watchLilNounsGovernorMaxQuorumVotesBpsSetEvent, // Actions event watcher for LilNounsGovernor.maxQuorumVotesBpsSet
  watchLilNounsGovernorMinQuorumVotesBpsSetEvent, // Actions event watcher for LilNounsGovernor.minQuorumVotesBpsSet
  watchLilNounsGovernorNewAdminEvent, // Actions event watcher for LilNounsGovernor.newAdmin
  watchLilNounsGovernorNewImplementationEvent, // Actions event watcher for LilNounsGovernor.newImplementation
  watchLilNounsGovernorNewPendingAdminEvent, // Actions event watcher for LilNounsGovernor.newPendingAdmin
  watchLilNounsGovernorNewPendingVetoerEvent, // Actions event watcher for LilNounsGovernor.newPendingVetoer
  watchLilNounsGovernorNewVetoerEvent, // Actions event watcher for LilNounsGovernor.newVetoer
  watchLilNounsGovernorProposalCanceledEvent, // Actions event watcher for LilNounsGovernor.proposalCanceled
  watchLilNounsGovernorProposalCreatedEvent, // Actions event watcher for LilNounsGovernor.proposalCreated
  watchLilNounsGovernorProposalCreatedWithRequirementsEvent, // Actions event watcher for LilNounsGovernor.proposalCreatedWithRequirements
  watchLilNounsGovernorProposalExecutedEvent, // Actions event watcher for LilNounsGovernor.proposalExecuted
  watchLilNounsGovernorProposalQueuedEvent, // Actions event watcher for LilNounsGovernor.proposalQueued
  watchLilNounsGovernorProposalThresholdBpsSetEvent, // Actions event watcher for LilNounsGovernor.proposalThresholdBpsSet
  watchLilNounsGovernorProposalVetoedEvent, // Actions event watcher for LilNounsGovernor.proposalVetoed
  watchLilNounsGovernorQuorumCoefficientSetEvent, // Actions event watcher for LilNounsGovernor.quorumCoefficientSet
  watchLilNounsGovernorQuorumVotesBpsSetEvent, // Actions event watcher for LilNounsGovernor.quorumVotesBpsSet
  watchLilNounsGovernorRefundableVoteEvent, // Actions event watcher for LilNounsGovernor.refundableVote
  watchLilNounsGovernorVoteCastEvent, // Actions event watcher for LilNounsGovernor.voteCast
  watchLilNounsGovernorVotingDelaySetEvent, // Actions event watcher for LilNounsGovernor.votingDelaySet
  watchLilNounsGovernorVotingPeriodSetEvent, // Actions event watcher for LilNounsGovernor.votingPeriodSet
  watchLilNounsGovernorWithdrawEvent, // Actions event watcher for LilNounsGovernor.withdraw
  watchLilNounsTokenApprovalEvent, // Actions event watcher for LilNounsToken.approval
  watchLilNounsTokenApprovalForAllEvent, // Actions event watcher for LilNounsToken.approvalForAll
  watchLilNounsTokenDelegateChangedEvent, // Actions event watcher for LilNounsToken.delegateChanged
  watchLilNounsTokenDelegateVotesChangedEvent, // Actions event watcher for LilNounsToken.delegateVotesChanged
  watchLilNounsTokenDescriptorLockedEvent, // Actions event watcher for LilNounsToken.descriptorLocked
  watchLilNounsTokenDescriptorUpdatedEvent, // Actions event watcher for LilNounsToken.descriptorUpdated
  watchLilNounsTokenEvent, // Actions event watcher for LilNounsToken
  watchLilNounsTokenLilNoundersDaoUpdatedEvent, // Actions event watcher for LilNounsToken.lilNoundersDaoUpdated
  watchLilNounsTokenMinterLockedEvent, // Actions event watcher for LilNounsToken.minterLocked
  watchLilNounsTokenMinterUpdatedEvent, // Actions event watcher for LilNounsToken.minterUpdated
  watchLilNounsTokenNounBurnedEvent, // Actions event watcher for LilNounsToken.nounBurned
  watchLilNounsTokenNounCreatedEvent, // Actions event watcher for LilNounsToken.nounCreated
  watchLilNounsTokenNounsDaoUpdatedEvent, // Actions event watcher for LilNounsToken.nounsDaoUpdated
  watchLilNounsTokenOwnershipTransferredEvent, // Actions event watcher for LilNounsToken.ownershipTransferred
  watchLilNounsTokenSeederLockedEvent, // Actions event watcher for LilNounsToken.seederLocked
  watchLilNounsTokenSeederUpdatedEvent, // Actions event watcher for LilNounsToken.seederUpdated
  watchLilNounsTokenTransferEvent, // Actions event watcher for LilNounsToken.transfer
  watchLilNounsTreasuryCancelTransactionEvent, // Actions event watcher for LilNounsTreasury.cancelTransaction
  watchLilNounsTreasuryEvent, // Actions event watcher for LilNounsTreasury
  watchLilNounsTreasuryExecuteTransactionEvent, // Actions event watcher for LilNounsTreasury.executeTransaction
  watchLilNounsTreasuryNewAdminEvent, // Actions event watcher for LilNounsTreasury.newAdmin
  watchLilNounsTreasuryNewDelayEvent, // Actions event watcher for LilNounsTreasury.newDelay
  watchLilNounsTreasuryNewPendingAdminEvent, // Actions event watcher for LilNounsTreasury.newPendingAdmin
  watchLilNounsTreasuryQueueTransactionEvent, // Actions event watcher for LilNounsTreasury.queueTransaction
  // Generated actions: write helpers
  writeLilNounsAuction, // Actions write helper for LilNounsAuction
  writeLilNounsAuctionBuyNow, // Actions write helper for LilNounsAuction.buyNow
  writeLilNounsAuctionInitialize, // Actions write helper for LilNounsAuction.initialize
  writeLilNounsAuctionPause, // Actions write helper for LilNounsAuction.pause
  writeLilNounsAuctionRenounceOwnership, // Actions write helper for LilNounsAuction.renounceOwnership
  writeLilNounsAuctionSetNounsDescriptor, // Actions write helper for LilNounsAuction.setNounsDescriptor
  writeLilNounsAuctionSetNounsSeeder, // Actions write helper for LilNounsAuction.setNounsSeeder
  writeLilNounsAuctionSetPoolSize, // Actions write helper for LilNounsAuction.setPoolSize
  writeLilNounsAuctionSetReservePrice, // Actions write helper for LilNounsAuction.setReservePrice
  writeLilNounsAuctionSetUpdateInterval, // Actions write helper for LilNounsAuction.setUpdateInterval
  writeLilNounsAuctionTransferOwnership, // Actions write helper for LilNounsAuction.transferOwnership
  writeLilNounsAuctionUnpause, // Actions write helper for LilNounsAuction.unpause
  writeLilNounsAuctionUpgradeTo, // Actions write helper for LilNounsAuction.upgradeTo
  writeLilNounsAuctionUpgradeToAndCall, // Actions write helper for LilNounsAuction.upgradeToAndCall
  writeLilNounsData, // Actions write helper for LilNounsData
  writeLilNounsDataAcceptOwnership, // Actions write helper for LilNounsData.acceptOwnership
  writeLilNounsDataCancelProposalCandidate, // Actions write helper for LilNounsData.cancelProposalCandidate
  writeLilNounsDataCreateProposalCandidate, // Actions write helper for LilNounsData.createProposalCandidate
  writeLilNounsDataInitialize, // Actions write helper for LilNounsData.initialize
  writeLilNounsDataInitializeV2, // Actions write helper for LilNounsData.initializeV2
  writeLilNounsDataRenounceOwnership, // Actions write helper for LilNounsData.renounceOwnership
  writeLilNounsDataSendCandidateFeedback, // Actions write helper for LilNounsData.sendCandidateFeedback
  writeLilNounsDataSendFeedback, // Actions write helper for LilNounsData.sendFeedback
  writeLilNounsDataSetCreateCandidateCost, // Actions write helper for LilNounsData.setCreateCandidateCost
  writeLilNounsDataSetFeeRecipient, // Actions write helper for LilNounsData.setFeeRecipient
  writeLilNounsDataSetUpdateCandidateCost, // Actions write helper for LilNounsData.setUpdateCandidateCost
  writeLilNounsDataTransferOwnership, // Actions write helper for LilNounsData.transferOwnership
  writeLilNounsDataUpdateProposalCandidate, // Actions write helper for LilNounsData.updateProposalCandidate
  writeLilNounsDataUpgradeToAndCall, // Actions write helper for LilNounsData.upgradeToAndCall
  writeLilNounsDataWithdrawEth, // Actions write helper for LilNounsData.withdrawEth
  writeLilNounsDescriptor, // Actions write helper for LilNounsDescriptor
  writeLilNounsDescriptorAddAccessories, // Actions write helper for LilNounsDescriptor.addAccessories
  writeLilNounsDescriptorAddAccessoriesFromPointer, // Actions write helper for LilNounsDescriptor.addAccessoriesFromPointer
  writeLilNounsDescriptorAddBackground, // Actions write helper for LilNounsDescriptor.addBackground
  writeLilNounsDescriptorAddBodies, // Actions write helper for LilNounsDescriptor.addBodies
  writeLilNounsDescriptorAddBodiesFromPointer, // Actions write helper for LilNounsDescriptor.addBodiesFromPointer
  writeLilNounsDescriptorAddGlasses, // Actions write helper for LilNounsDescriptor.addGlasses
  writeLilNounsDescriptorAddGlassesFromPointer, // Actions write helper for LilNounsDescriptor.addGlassesFromPointer
  writeLilNounsDescriptorAddHeads, // Actions write helper for LilNounsDescriptor.addHeads
  writeLilNounsDescriptorAddHeadsFromPointer, // Actions write helper for LilNounsDescriptor.addHeadsFromPointer
  writeLilNounsDescriptorAddManyBackgrounds, // Actions write helper for LilNounsDescriptor.addManyBackgrounds
  writeLilNounsDescriptorLockParts, // Actions write helper for LilNounsDescriptor.lockParts
  writeLilNounsDescriptorRenounceOwnership, // Actions write helper for LilNounsDescriptor.renounceOwnership
  writeLilNounsDescriptorSetArt, // Actions write helper for LilNounsDescriptor.setArt
  writeLilNounsDescriptorSetArtDescriptor, // Actions write helper for LilNounsDescriptor.setArtDescriptor
  writeLilNounsDescriptorSetArtInflator, // Actions write helper for LilNounsDescriptor.setArtInflator
  writeLilNounsDescriptorSetBaseUri, // Actions write helper for LilNounsDescriptor.setBaseUri
  writeLilNounsDescriptorSetPalette, // Actions write helper for LilNounsDescriptor.setPalette
  writeLilNounsDescriptorSetPalettePointer, // Actions write helper for LilNounsDescriptor.setPalettePointer
  writeLilNounsDescriptorSetRenderer, // Actions write helper for LilNounsDescriptor.setRenderer
  writeLilNounsDescriptorToggleDataUriEnabled, // Actions write helper for LilNounsDescriptor.toggleDataUriEnabled
  writeLilNounsDescriptorTransferOwnership, // Actions write helper for LilNounsDescriptor.transferOwnership
  writeLilNounsEnsMapper, // Actions write helper for LilNounsEnsMapper
  writeLilNounsEnsMapperClaimSubname, // Actions write helper for LilNounsEnsMapper.claimSubname
  writeLilNounsEnsMapperEmitAddrEvents, // Actions write helper for LilNounsEnsMapper.emitAddrEvents
  writeLilNounsEnsMapperEmitTextEvents, // Actions write helper for LilNounsEnsMapper.emitTextEvents
  writeLilNounsEnsMapperInitialize, // Actions write helper for LilNounsEnsMapper.initialize
  writeLilNounsEnsMapperMigrateLegacySubname, // Actions write helper for LilNounsEnsMapper.migrateLegacySubname
  writeLilNounsEnsMapperReleaseLegacySubname, // Actions write helper for LilNounsEnsMapper.releaseLegacySubname
  writeLilNounsEnsMapperRelinquishSubname, // Actions write helper for LilNounsEnsMapper.relinquishSubname
  writeLilNounsEnsMapperRenounceOwnership, // Actions write helper for LilNounsEnsMapper.renounceOwnership
  writeLilNounsEnsMapperRestoreResolver, // Actions write helper for LilNounsEnsMapper.restoreResolver
  writeLilNounsEnsMapperSetText, // Actions write helper for LilNounsEnsMapper.setText
  writeLilNounsEnsMapperTransferOwnership, // Actions write helper for LilNounsEnsMapper.transferOwnership
  writeLilNounsEnsMapperUpgradeToAndCall, // Actions write helper for LilNounsEnsMapper.upgradeToAndCall
  writeLilNounsGovernor, // Actions write helper for LilNounsGovernor
  writeLilNounsGovernorAcceptAdmin, // Actions write helper for LilNounsGovernor.acceptAdmin
  writeLilNounsGovernorAcceptVetoer, // Actions write helper for LilNounsGovernor.acceptVetoer
  writeLilNounsGovernorBurnVetoPower, // Actions write helper for LilNounsGovernor.burnVetoPower
  writeLilNounsGovernorCancel, // Actions write helper for LilNounsGovernor.cancel
  writeLilNounsGovernorCastRefundableVote, // Actions write helper for LilNounsGovernor.castRefundableVote
  writeLilNounsGovernorCastRefundableVoteWithReason, // Actions write helper for LilNounsGovernor.castRefundableVoteWithReason
  writeLilNounsGovernorCastVote, // Actions write helper for LilNounsGovernor.castVote
  writeLilNounsGovernorCastVoteBySig, // Actions write helper for LilNounsGovernor.castVoteBySig
  writeLilNounsGovernorCastVoteWithReason, // Actions write helper for LilNounsGovernor.castVoteWithReason
  writeLilNounsGovernorExecute, // Actions write helper for LilNounsGovernor.execute
  writeLilNounsGovernorInitialize, // Actions write helper for LilNounsGovernor.initialize
  writeLilNounsGovernorPropose, // Actions write helper for LilNounsGovernor.propose
  writeLilNounsGovernorQueue, // Actions write helper for LilNounsGovernor.queue
  writeLilNounsGovernorSetDynamicQuorumParams, // Actions write helper for LilNounsGovernor.setDynamicQuorumParams
  writeLilNounsGovernorSetMaxQuorumVotesBps, // Actions write helper for LilNounsGovernor.setMaxQuorumVotesBps
  writeLilNounsGovernorSetMinQuorumVotesBps, // Actions write helper for LilNounsGovernor.setMinQuorumVotesBps
  writeLilNounsGovernorSetPendingAdmin, // Actions write helper for LilNounsGovernor.setPendingAdmin
  writeLilNounsGovernorSetPendingVetoer, // Actions write helper for LilNounsGovernor.setPendingVetoer
  writeLilNounsGovernorSetProposalThresholdBps, // Actions write helper for LilNounsGovernor.setProposalThresholdBps
  writeLilNounsGovernorSetQuorumCoefficient, // Actions write helper for LilNounsGovernor.setQuorumCoefficient
  writeLilNounsGovernorSetVotingDelay, // Actions write helper for LilNounsGovernor.setVotingDelay
  writeLilNounsGovernorSetVotingPeriod, // Actions write helper for LilNounsGovernor.setVotingPeriod
  writeLilNounsGovernorVeto, // Actions write helper for LilNounsGovernor.veto
  writeLilNounsGovernorWithdraw, // Actions write helper for LilNounsGovernor.withdraw
  writeLilNounsToken, // Actions write helper for LilNounsToken
  writeLilNounsTokenApprove, // Actions write helper for LilNounsToken.approve
  writeLilNounsTokenBurn, // Actions write helper for LilNounsToken.burn
  writeLilNounsTokenDelegate, // Actions write helper for LilNounsToken.delegate
  writeLilNounsTokenDelegateBySig, // Actions write helper for LilNounsToken.delegateBySig
  writeLilNounsTokenLockDescriptor, // Actions write helper for LilNounsToken.lockDescriptor
  writeLilNounsTokenLockMinter, // Actions write helper for LilNounsToken.lockMinter
  writeLilNounsTokenLockSeeder, // Actions write helper for LilNounsToken.lockSeeder
  writeLilNounsTokenMint, // Actions write helper for LilNounsToken.mint
  writeLilNounsTokenRenounceOwnership, // Actions write helper for LilNounsToken.renounceOwnership
  writeLilNounsTokenSafeTransferFrom, // Actions write helper for LilNounsToken.safeTransferFrom
  writeLilNounsTokenSetApprovalForAll, // Actions write helper for LilNounsToken.setApprovalForAll
  writeLilNounsTokenSetContractUriHash, // Actions write helper for LilNounsToken.setContractUriHash
  writeLilNounsTokenSetDescriptor, // Actions write helper for LilNounsToken.setDescriptor
  writeLilNounsTokenSetLilNoundersDao, // Actions write helper for LilNounsToken.setLilNoundersDao
  writeLilNounsTokenSetMinter, // Actions write helper for LilNounsToken.setMinter
  writeLilNounsTokenSetNounsDao, // Actions write helper for LilNounsToken.setNounsDao
  writeLilNounsTokenSetSeeder, // Actions write helper for LilNounsToken.setSeeder
  writeLilNounsTokenTransferFrom, // Actions write helper for LilNounsToken.transferFrom
  writeLilNounsTokenTransferOwnership, // Actions write helper for LilNounsToken.transferOwnership
  writeLilNounsTreasury, // Actions write helper for LilNounsTreasury
  writeLilNounsTreasuryAcceptAdmin, // Actions write helper for LilNounsTreasury.acceptAdmin
  writeLilNounsTreasuryCancelTransaction, // Actions write helper for LilNounsTreasury.cancelTransaction
  writeLilNounsTreasuryExecuteTransaction, // Actions write helper for LilNounsTreasury.executeTransaction
  writeLilNounsTreasuryQueueTransaction, // Actions write helper for LilNounsTreasury.queueTransaction
  writeLilNounsTreasurySetDelay, // Actions write helper for LilNounsTreasury.setDelay
  writeLilNounsTreasurySetPendingAdmin, // Actions write helper for LilNounsTreasury.setPendingAdmin
} from "./actions.gen";

export {
  // Generated React hooks: read helpers
  useReadLilNounsAuction, // React read hook for LilNounsAuction
  useReadLilNounsAuctionFetchNextNoun, // React read hook for LilNounsAuction.fetchNextNoun
  useReadLilNounsAuctionFetchNoun, // React read hook for LilNounsAuction.fetchNoun
  useReadLilNounsAuctionGetCurrentVrgdaPrice, // React read hook for LilNounsAuction.getCurrentVrgdaPrice
  useReadLilNounsAuctionGetSeederBlockNumber, // React read hook for LilNounsAuction.getSeederBlockNumber
  useReadLilNounsAuctionGetTargetSaleTime, // React read hook for LilNounsAuction.getTargetSaleTime
  useReadLilNounsAuctionGetVrgdaPrice, // React read hook for LilNounsAuction.getVrgdaPrice
  useReadLilNounsAuctionLilNounderRewardNouns, // React read hook for LilNounsAuction.lilNounderRewardNouns
  useReadLilNounsAuctionNextNounId, // React read hook for LilNounsAuction.nextNounId
  useReadLilNounsAuctionNextNounIdForCaller, // React read hook for LilNounsAuction.nextNounIdForCaller
  useReadLilNounsAuctionNounsDaoRewardNouns, // React read hook for LilNounsAuction.nounsDaoRewardNouns
  useReadLilNounsAuctionNounsDescriptor, // React read hook for LilNounsAuction.nounsDescriptor
  useReadLilNounsAuctionNounsSeeder, // React read hook for LilNounsAuction.nounsSeeder
  useReadLilNounsAuctionNounsSoldAtAuction, // React read hook for LilNounsAuction.nounsSoldAtAuction
  useReadLilNounsAuctionNounsToken, // React read hook for LilNounsAuction.nounsToken
  useReadLilNounsAuctionOwner, // React read hook for LilNounsAuction.owner
  useReadLilNounsAuctionPaused, // React read hook for LilNounsAuction.paused
  useReadLilNounsAuctionPoolSize, // React read hook for LilNounsAuction.poolSize
  useReadLilNounsAuctionProxiableUuid, // React read hook for LilNounsAuction.proxiableUuid
  useReadLilNounsAuctionReservePrice, // React read hook for LilNounsAuction.reservePrice
  useReadLilNounsAuctionSeederBlockNumber, // React read hook for LilNounsAuction.seederBlockNumber
  useReadLilNounsAuctionStartTime, // React read hook for LilNounsAuction.startTime
  useReadLilNounsAuctionTargetPrice, // React read hook for LilNounsAuction.targetPrice
  useReadLilNounsAuctionUpdateInterval, // React read hook for LilNounsAuction.updateInterval
  useReadLilNounsAuctionUsedBlockNumbers, // React read hook for LilNounsAuction.usedBlockNumbers
  useReadLilNounsAuctionWethAddress, // React read hook for LilNounsAuction.wethAddress
  useReadLilNounsData, // React read hook for LilNounsData
  useReadLilNounsDataCreateCandidateCost, // React read hook for LilNounsData.createCandidateCost
  useReadLilNounsDataFeeRecipient, // React read hook for LilNounsData.feeRecipient
  useReadLilNounsDataMaxProposalCalls, // React read hook for LilNounsData.maxProposalCalls
  useReadLilNounsDataOwner, // React read hook for LilNounsData.owner
  useReadLilNounsDataPendingOwner, // React read hook for LilNounsData.pendingOwner
  useReadLilNounsDataPriorVotesBlocksAgo, // React read hook for LilNounsData.priorVotesBlocksAgo
  useReadLilNounsDataPropCandidates, // React read hook for LilNounsData.propCandidates
  useReadLilNounsDataProxiableUuid, // React read hook for LilNounsData.proxiableUuid
  useReadLilNounsDataToken, // React read hook for LilNounsData.token
  useReadLilNounsDataUpdateCandidateCost, // React read hook for LilNounsData.updateCandidateCost
  useReadLilNounsDataUpgradeInterfaceVersion, // React read hook for LilNounsData.upgradeInterfaceVersion
  useReadLilNounsDescriptor, // React read hook for LilNounsDescriptor
  useReadLilNounsDescriptorAccessories, // React read hook for LilNounsDescriptor.accessories
  useReadLilNounsDescriptorAccessoryCount, // React read hook for LilNounsDescriptor.accessoryCount
  useReadLilNounsDescriptorArePartsLocked, // React read hook for LilNounsDescriptor.arePartsLocked
  useReadLilNounsDescriptorArt, // React read hook for LilNounsDescriptor.art
  useReadLilNounsDescriptorBackgroundCount, // React read hook for LilNounsDescriptor.backgroundCount
  useReadLilNounsDescriptorBackgrounds, // React read hook for LilNounsDescriptor.backgrounds
  useReadLilNounsDescriptorBaseUri, // React read hook for LilNounsDescriptor.baseUri
  useReadLilNounsDescriptorBodies, // React read hook for LilNounsDescriptor.bodies
  useReadLilNounsDescriptorBodyCount, // React read hook for LilNounsDescriptor.bodyCount
  useReadLilNounsDescriptorDataUri, // React read hook for LilNounsDescriptor.dataUri
  useReadLilNounsDescriptorGenerateSvgImage, // React read hook for LilNounsDescriptor.generateSvgImage
  useReadLilNounsDescriptorGenericDataUri, // React read hook for LilNounsDescriptor.genericDataUri
  useReadLilNounsDescriptorGetPartsForSeed, // React read hook for LilNounsDescriptor.getPartsForSeed
  useReadLilNounsDescriptorGlasses, // React read hook for LilNounsDescriptor.glasses
  useReadLilNounsDescriptorGlassesCount, // React read hook for LilNounsDescriptor.glassesCount
  useReadLilNounsDescriptorHeadCount, // React read hook for LilNounsDescriptor.headCount
  useReadLilNounsDescriptorHeads, // React read hook for LilNounsDescriptor.heads
  useReadLilNounsDescriptorIsDataUriEnabled, // React read hook for LilNounsDescriptor.isDataUriEnabled
  useReadLilNounsDescriptorOwner, // React read hook for LilNounsDescriptor.owner
  useReadLilNounsDescriptorPalettes, // React read hook for LilNounsDescriptor.palettes
  useReadLilNounsDescriptorRenderer, // React read hook for LilNounsDescriptor.renderer
  useReadLilNounsDescriptorTokenUri, // React read hook for LilNounsDescriptor.tokenUri
  useReadLilNounsEnsMapper, // React read hook for LilNounsEnsMapper
  useReadLilNounsEnsMapperAddr, // React read hook for LilNounsEnsMapper.addr
  useReadLilNounsEnsMapperEns, // React read hook for LilNounsEnsMapper.ens
  useReadLilNounsEnsMapperEnsNameOf, // React read hook for LilNounsEnsMapper.ensNameOf
  useReadLilNounsEnsMapperEnsNodeOf, // React read hook for LilNounsEnsMapper.ensNodeOf
  useReadLilNounsEnsMapperIsLegacyNode, // React read hook for LilNounsEnsMapper.isLegacyNode
  useReadLilNounsEnsMapperLegacy, // React read hook for LilNounsEnsMapper.legacy
  useReadLilNounsEnsMapperName, // React read hook for LilNounsEnsMapper.name
  useReadLilNounsEnsMapperNft, // React read hook for LilNounsEnsMapper.nft
  useReadLilNounsEnsMapperOwner, // React read hook for LilNounsEnsMapper.owner
  useReadLilNounsEnsMapperProxiableUuid, // React read hook for LilNounsEnsMapper.proxiableUuid
  useReadLilNounsEnsMapperRootLabel, // React read hook for LilNounsEnsMapper.rootLabel
  useReadLilNounsEnsMapperRootNode, // React read hook for LilNounsEnsMapper.rootNode
  useReadLilNounsEnsMapperSupportsInterface, // React read hook for LilNounsEnsMapper.supportsInterface
  useReadLilNounsEnsMapperText, // React read hook for LilNounsEnsMapper.text
  useReadLilNounsEnsMapperUpgradeInterfaceVersion, // React read hook for LilNounsEnsMapper.upgradeInterfaceVersion
  useReadLilNounsGovernor, // React read hook for LilNounsGovernor
  useReadLilNounsGovernorAdmin, // React read hook for LilNounsGovernor.admin
  useReadLilNounsGovernorBallotTypehash, // React read hook for LilNounsGovernor.ballotTypehash
  useReadLilNounsGovernorDomainTypehash, // React read hook for LilNounsGovernor.domainTypehash
  useReadLilNounsGovernorDynamicQuorumVotes, // React read hook for LilNounsGovernor.dynamicQuorumVotes
  useReadLilNounsGovernorGetActions, // React read hook for LilNounsGovernor.getActions
  useReadLilNounsGovernorGetDynamicQuorumParamsAt, // React read hook for LilNounsGovernor.getDynamicQuorumParamsAt
  useReadLilNounsGovernorGetReceipt, // React read hook for LilNounsGovernor.getReceipt
  useReadLilNounsGovernorImplementation, // React read hook for LilNounsGovernor.implementation
  useReadLilNounsGovernorLatestProposalIds, // React read hook for LilNounsGovernor.latestProposalIds
  useReadLilNounsGovernorMaxProposalThresholdBps, // React read hook for LilNounsGovernor.maxProposalThresholdBps
  useReadLilNounsGovernorMaxQuorumVotes, // React read hook for LilNounsGovernor.maxQuorumVotes
  useReadLilNounsGovernorMaxQuorumVotesBps, // React read hook for LilNounsGovernor.maxQuorumVotesBps
  useReadLilNounsGovernorMaxQuorumVotesBpsUpperBound, // React read hook for LilNounsGovernor.maxQuorumVotesBpsUpperBound
  useReadLilNounsGovernorMaxRefundBaseFee, // React read hook for LilNounsGovernor.maxRefundBaseFee
  useReadLilNounsGovernorMaxRefundGasUsed, // React read hook for LilNounsGovernor.maxRefundGasUsed
  useReadLilNounsGovernorMaxRefundPriorityFee, // React read hook for LilNounsGovernor.maxRefundPriorityFee
  useReadLilNounsGovernorMaxVotingDelay, // React read hook for LilNounsGovernor.maxVotingDelay
  useReadLilNounsGovernorMaxVotingPeriod, // React read hook for LilNounsGovernor.maxVotingPeriod
  useReadLilNounsGovernorMinProposalThresholdBps, // React read hook for LilNounsGovernor.minProposalThresholdBps
  useReadLilNounsGovernorMinQuorumVotes, // React read hook for LilNounsGovernor.minQuorumVotes
  useReadLilNounsGovernorMinQuorumVotesBpsLowerBound, // React read hook for LilNounsGovernor.minQuorumVotesBpsLowerBound
  useReadLilNounsGovernorMinQuorumVotesBpsUpperBound, // React read hook for LilNounsGovernor.minQuorumVotesBpsUpperBound
  useReadLilNounsGovernorMinVotingDelay, // React read hook for LilNounsGovernor.minVotingDelay
  useReadLilNounsGovernorMinVotingPeriod, // React read hook for LilNounsGovernor.minVotingPeriod
  useReadLilNounsGovernorName, // React read hook for LilNounsGovernor.name
  useReadLilNounsGovernorNouns, // React read hook for LilNounsGovernor.nouns
  useReadLilNounsGovernorPendingAdmin, // React read hook for LilNounsGovernor.pendingAdmin
  useReadLilNounsGovernorPendingVetoer, // React read hook for LilNounsGovernor.pendingVetoer
  useReadLilNounsGovernorProposalCount, // React read hook for LilNounsGovernor.proposalCount
  useReadLilNounsGovernorProposalMaxOperations, // React read hook for LilNounsGovernor.proposalMaxOperations
  useReadLilNounsGovernorProposals, // React read hook for LilNounsGovernor.proposals
  useReadLilNounsGovernorProposalThreshold, // React read hook for LilNounsGovernor.proposalThreshold
  useReadLilNounsGovernorProposalThresholdBps, // React read hook for LilNounsGovernor.proposalThresholdBps
  useReadLilNounsGovernorQuorumParamsCheckpoints, // React read hook for LilNounsGovernor.quorumParamsCheckpoints
  useReadLilNounsGovernorQuorumVotes, // React read hook for LilNounsGovernor.quorumVotes
  useReadLilNounsGovernorQuorumVotesBps, // React read hook for LilNounsGovernor.quorumVotesBps
  useReadLilNounsGovernorRefundBaseGas, // React read hook for LilNounsGovernor.refundBaseGas
  useReadLilNounsGovernorState, // React read hook for LilNounsGovernor.state
  useReadLilNounsGovernorTimelock, // React read hook for LilNounsGovernor.timelock
  useReadLilNounsGovernorVetoer, // React read hook for LilNounsGovernor.vetoer
  useReadLilNounsGovernorVotingDelay, // React read hook for LilNounsGovernor.votingDelay
  useReadLilNounsGovernorVotingPeriod, // React read hook for LilNounsGovernor.votingPeriod
  useReadLilNounsToken, // React read hook for LilNounsToken
  useReadLilNounsTokenBalanceOf, // React read hook for LilNounsToken.balanceOf
  useReadLilNounsTokenCheckpoints, // React read hook for LilNounsToken.checkpoints
  useReadLilNounsTokenContractUri, // React read hook for LilNounsToken.contractUri
  useReadLilNounsTokenDataUri, // React read hook for LilNounsToken.dataUri
  useReadLilNounsTokenDecimals, // React read hook for LilNounsToken.decimals
  useReadLilNounsTokenDelegates, // React read hook for LilNounsToken.delegates
  useReadLilNounsTokenDelegationTypehash, // React read hook for LilNounsToken.delegationTypehash
  useReadLilNounsTokenDescriptor, // React read hook for LilNounsToken.descriptor
  useReadLilNounsTokenDomainTypehash, // React read hook for LilNounsToken.domainTypehash
  useReadLilNounsTokenGetApproved, // React read hook for LilNounsToken.getApproved
  useReadLilNounsTokenGetCurrentVotes, // React read hook for LilNounsToken.getCurrentVotes
  useReadLilNounsTokenGetPriorVotes, // React read hook for LilNounsToken.getPriorVotes
  useReadLilNounsTokenIsApprovedForAll, // React read hook for LilNounsToken.isApprovedForAll
  useReadLilNounsTokenIsDescriptorLocked, // React read hook for LilNounsToken.isDescriptorLocked
  useReadLilNounsTokenIsMinterLocked, // React read hook for LilNounsToken.isMinterLocked
  useReadLilNounsTokenIsSeederLocked, // React read hook for LilNounsToken.isSeederLocked
  useReadLilNounsTokenLilnoundersDao, // React read hook for LilNounsToken.lilnoundersDao
  useReadLilNounsTokenMinter, // React read hook for LilNounsToken.minter
  useReadLilNounsTokenName, // React read hook for LilNounsToken.name
  useReadLilNounsTokenNonces, // React read hook for LilNounsToken.nonces
  useReadLilNounsTokenNounsDao, // React read hook for LilNounsToken.nounsDao
  useReadLilNounsTokenNumCheckpoints, // React read hook for LilNounsToken.numCheckpoints
  useReadLilNounsTokenOwner, // React read hook for LilNounsToken.owner
  useReadLilNounsTokenOwnerOf, // React read hook for LilNounsToken.ownerOf
  useReadLilNounsTokenProxyRegistry, // React read hook for LilNounsToken.proxyRegistry
  useReadLilNounsTokenSeeder, // React read hook for LilNounsToken.seeder
  useReadLilNounsTokenSeeds, // React read hook for LilNounsToken.seeds
  useReadLilNounsTokenSupportsInterface, // React read hook for LilNounsToken.supportsInterface
  useReadLilNounsTokenSymbol, // React read hook for LilNounsToken.symbol
  useReadLilNounsTokenTokenByIndex, // React read hook for LilNounsToken.tokenByIndex
  useReadLilNounsTokenTokenOfOwnerByIndex, // React read hook for LilNounsToken.tokenOfOwnerByIndex
  useReadLilNounsTokenTokenUri, // React read hook for LilNounsToken.tokenUri
  useReadLilNounsTokenTotalSupply, // React read hook for LilNounsToken.totalSupply
  useReadLilNounsTokenVotesToDelegate, // React read hook for LilNounsToken.votesToDelegate
  useReadLilNounsTreasury, // React read hook for LilNounsTreasury
  useReadLilNounsTreasuryAdmin, // React read hook for LilNounsTreasury.admin
  useReadLilNounsTreasuryDelay, // React read hook for LilNounsTreasury.delay
  useReadLilNounsTreasuryGracePeriod, // React read hook for LilNounsTreasury.gracePeriod
  useReadLilNounsTreasuryMaximumDelay, // React read hook for LilNounsTreasury.maximumDelay
  useReadLilNounsTreasuryMinimumDelay, // React read hook for LilNounsTreasury.minimumDelay
  useReadLilNounsTreasuryPendingAdmin, // React read hook for LilNounsTreasury.pendingAdmin
  useReadLilNounsTreasuryQueuedTransactions, // React read hook for LilNounsTreasury.queuedTransactions
  // Generated React hooks: simulate helpers
  useSimulateLilNounsAuction, // React simulate hook for LilNounsAuction
  useSimulateLilNounsAuctionBuyNow, // React simulate hook for LilNounsAuction.buyNow
  useSimulateLilNounsAuctionInitialize, // React simulate hook for LilNounsAuction.initialize
  useSimulateLilNounsAuctionPause, // React simulate hook for LilNounsAuction.pause
  useSimulateLilNounsAuctionRenounceOwnership, // React simulate hook for LilNounsAuction.renounceOwnership
  useSimulateLilNounsAuctionSetNounsDescriptor, // React simulate hook for LilNounsAuction.setNounsDescriptor
  useSimulateLilNounsAuctionSetNounsSeeder, // React simulate hook for LilNounsAuction.setNounsSeeder
  useSimulateLilNounsAuctionSetPoolSize, // React simulate hook for LilNounsAuction.setPoolSize
  useSimulateLilNounsAuctionSetReservePrice, // React simulate hook for LilNounsAuction.setReservePrice
  useSimulateLilNounsAuctionSetUpdateInterval, // React simulate hook for LilNounsAuction.setUpdateInterval
  useSimulateLilNounsAuctionTransferOwnership, // React simulate hook for LilNounsAuction.transferOwnership
  useSimulateLilNounsAuctionUnpause, // React simulate hook for LilNounsAuction.unpause
  useSimulateLilNounsAuctionUpgradeTo, // React simulate hook for LilNounsAuction.upgradeTo
  useSimulateLilNounsAuctionUpgradeToAndCall, // React simulate hook for LilNounsAuction.upgradeToAndCall
  useSimulateLilNounsData, // React simulate hook for LilNounsData
  useSimulateLilNounsDataAcceptOwnership, // React simulate hook for LilNounsData.acceptOwnership
  useSimulateLilNounsDataCancelProposalCandidate, // React simulate hook for LilNounsData.cancelProposalCandidate
  useSimulateLilNounsDataCreateProposalCandidate, // React simulate hook for LilNounsData.createProposalCandidate
  useSimulateLilNounsDataInitialize, // React simulate hook for LilNounsData.initialize
  useSimulateLilNounsDataInitializeV2, // React simulate hook for LilNounsData.initializeV2
  useSimulateLilNounsDataRenounceOwnership, // React simulate hook for LilNounsData.renounceOwnership
  useSimulateLilNounsDataSendCandidateFeedback, // React simulate hook for LilNounsData.sendCandidateFeedback
  useSimulateLilNounsDataSendFeedback, // React simulate hook for LilNounsData.sendFeedback
  useSimulateLilNounsDataSetCreateCandidateCost, // React simulate hook for LilNounsData.setCreateCandidateCost
  useSimulateLilNounsDataSetFeeRecipient, // React simulate hook for LilNounsData.setFeeRecipient
  useSimulateLilNounsDataSetUpdateCandidateCost, // React simulate hook for LilNounsData.setUpdateCandidateCost
  useSimulateLilNounsDataTransferOwnership, // React simulate hook for LilNounsData.transferOwnership
  useSimulateLilNounsDataUpdateProposalCandidate, // React simulate hook for LilNounsData.updateProposalCandidate
  useSimulateLilNounsDataUpgradeToAndCall, // React simulate hook for LilNounsData.upgradeToAndCall
  useSimulateLilNounsDataWithdrawEth, // React simulate hook for LilNounsData.withdrawEth
  useSimulateLilNounsDescriptor, // React simulate hook for LilNounsDescriptor
  useSimulateLilNounsDescriptorAddAccessories, // React simulate hook for LilNounsDescriptor.addAccessories
  useSimulateLilNounsDescriptorAddAccessoriesFromPointer, // React simulate hook for LilNounsDescriptor.addAccessoriesFromPointer
  useSimulateLilNounsDescriptorAddBackground, // React simulate hook for LilNounsDescriptor.addBackground
  useSimulateLilNounsDescriptorAddBodies, // React simulate hook for LilNounsDescriptor.addBodies
  useSimulateLilNounsDescriptorAddBodiesFromPointer, // React simulate hook for LilNounsDescriptor.addBodiesFromPointer
  useSimulateLilNounsDescriptorAddGlasses, // React simulate hook for LilNounsDescriptor.addGlasses
  useSimulateLilNounsDescriptorAddGlassesFromPointer, // React simulate hook for LilNounsDescriptor.addGlassesFromPointer
  useSimulateLilNounsDescriptorAddHeads, // React simulate hook for LilNounsDescriptor.addHeads
  useSimulateLilNounsDescriptorAddHeadsFromPointer, // React simulate hook for LilNounsDescriptor.addHeadsFromPointer
  useSimulateLilNounsDescriptorAddManyBackgrounds, // React simulate hook for LilNounsDescriptor.addManyBackgrounds
  useSimulateLilNounsDescriptorLockParts, // React simulate hook for LilNounsDescriptor.lockParts
  useSimulateLilNounsDescriptorRenounceOwnership, // React simulate hook for LilNounsDescriptor.renounceOwnership
  useSimulateLilNounsDescriptorSetArt, // React simulate hook for LilNounsDescriptor.setArt
  useSimulateLilNounsDescriptorSetArtDescriptor, // React simulate hook for LilNounsDescriptor.setArtDescriptor
  useSimulateLilNounsDescriptorSetArtInflator, // React simulate hook for LilNounsDescriptor.setArtInflator
  useSimulateLilNounsDescriptorSetBaseUri, // React simulate hook for LilNounsDescriptor.setBaseUri
  useSimulateLilNounsDescriptorSetPalette, // React simulate hook for LilNounsDescriptor.setPalette
  useSimulateLilNounsDescriptorSetPalettePointer, // React simulate hook for LilNounsDescriptor.setPalettePointer
  useSimulateLilNounsDescriptorSetRenderer, // React simulate hook for LilNounsDescriptor.setRenderer
  useSimulateLilNounsDescriptorToggleDataUriEnabled, // React simulate hook for LilNounsDescriptor.toggleDataUriEnabled
  useSimulateLilNounsDescriptorTransferOwnership, // React simulate hook for LilNounsDescriptor.transferOwnership
  useSimulateLilNounsEnsMapper, // React simulate hook for LilNounsEnsMapper
  useSimulateLilNounsEnsMapperClaimSubname, // React simulate hook for LilNounsEnsMapper.claimSubname
  useSimulateLilNounsEnsMapperEmitAddrEvents, // React simulate hook for LilNounsEnsMapper.emitAddrEvents
  useSimulateLilNounsEnsMapperEmitTextEvents, // React simulate hook for LilNounsEnsMapper.emitTextEvents
  useSimulateLilNounsEnsMapperInitialize, // React simulate hook for LilNounsEnsMapper.initialize
  useSimulateLilNounsEnsMapperMigrateLegacySubname, // React simulate hook for LilNounsEnsMapper.migrateLegacySubname
  useSimulateLilNounsEnsMapperReleaseLegacySubname, // React simulate hook for LilNounsEnsMapper.releaseLegacySubname
  useSimulateLilNounsEnsMapperRelinquishSubname, // React simulate hook for LilNounsEnsMapper.relinquishSubname
  useSimulateLilNounsEnsMapperRenounceOwnership, // React simulate hook for LilNounsEnsMapper.renounceOwnership
  useSimulateLilNounsEnsMapperRestoreResolver, // React simulate hook for LilNounsEnsMapper.restoreResolver
  useSimulateLilNounsEnsMapperSetText, // React simulate hook for LilNounsEnsMapper.setText
  useSimulateLilNounsEnsMapperTransferOwnership, // React simulate hook for LilNounsEnsMapper.transferOwnership
  useSimulateLilNounsEnsMapperUpgradeToAndCall, // React simulate hook for LilNounsEnsMapper.upgradeToAndCall
  useSimulateLilNounsGovernor, // React simulate hook for LilNounsGovernor
  useSimulateLilNounsGovernorAcceptAdmin, // React simulate hook for LilNounsGovernor.acceptAdmin
  useSimulateLilNounsGovernorAcceptVetoer, // React simulate hook for LilNounsGovernor.acceptVetoer
  useSimulateLilNounsGovernorBurnVetoPower, // React simulate hook for LilNounsGovernor.burnVetoPower
  useSimulateLilNounsGovernorCancel, // React simulate hook for LilNounsGovernor.cancel
  useSimulateLilNounsGovernorCastRefundableVote, // React simulate hook for LilNounsGovernor.castRefundableVote
  useSimulateLilNounsGovernorCastRefundableVoteWithReason, // React simulate hook for LilNounsGovernor.castRefundableVoteWithReason
  useSimulateLilNounsGovernorCastVote, // React simulate hook for LilNounsGovernor.castVote
  useSimulateLilNounsGovernorCastVoteBySig, // React simulate hook for LilNounsGovernor.castVoteBySig
  useSimulateLilNounsGovernorCastVoteWithReason, // React simulate hook for LilNounsGovernor.castVoteWithReason
  useSimulateLilNounsGovernorExecute, // React simulate hook for LilNounsGovernor.execute
  useSimulateLilNounsGovernorInitialize, // React simulate hook for LilNounsGovernor.initialize
  useSimulateLilNounsGovernorPropose, // React simulate hook for LilNounsGovernor.propose
  useSimulateLilNounsGovernorQueue, // React simulate hook for LilNounsGovernor.queue
  useSimulateLilNounsGovernorSetDynamicQuorumParams, // React simulate hook for LilNounsGovernor.setDynamicQuorumParams
  useSimulateLilNounsGovernorSetMaxQuorumVotesBps, // React simulate hook for LilNounsGovernor.setMaxQuorumVotesBps
  useSimulateLilNounsGovernorSetMinQuorumVotesBps, // React simulate hook for LilNounsGovernor.setMinQuorumVotesBps
  useSimulateLilNounsGovernorSetPendingAdmin, // React simulate hook for LilNounsGovernor.setPendingAdmin
  useSimulateLilNounsGovernorSetPendingVetoer, // React simulate hook for LilNounsGovernor.setPendingVetoer
  useSimulateLilNounsGovernorSetProposalThresholdBps, // React simulate hook for LilNounsGovernor.setProposalThresholdBps
  useSimulateLilNounsGovernorSetQuorumCoefficient, // React simulate hook for LilNounsGovernor.setQuorumCoefficient
  useSimulateLilNounsGovernorSetVotingDelay, // React simulate hook for LilNounsGovernor.setVotingDelay
  useSimulateLilNounsGovernorSetVotingPeriod, // React simulate hook for LilNounsGovernor.setVotingPeriod
  useSimulateLilNounsGovernorVeto, // React simulate hook for LilNounsGovernor.veto
  useSimulateLilNounsGovernorWithdraw, // React simulate hook for LilNounsGovernor.withdraw
  useSimulateLilNounsToken, // React simulate hook for LilNounsToken
  useSimulateLilNounsTokenApprove, // React simulate hook for LilNounsToken.approve
  useSimulateLilNounsTokenBurn, // React simulate hook for LilNounsToken.burn
  useSimulateLilNounsTokenDelegate, // React simulate hook for LilNounsToken.delegate
  useSimulateLilNounsTokenDelegateBySig, // React simulate hook for LilNounsToken.delegateBySig
  useSimulateLilNounsTokenLockDescriptor, // React simulate hook for LilNounsToken.lockDescriptor
  useSimulateLilNounsTokenLockMinter, // React simulate hook for LilNounsToken.lockMinter
  useSimulateLilNounsTokenLockSeeder, // React simulate hook for LilNounsToken.lockSeeder
  useSimulateLilNounsTokenMint, // React simulate hook for LilNounsToken.mint
  useSimulateLilNounsTokenRenounceOwnership, // React simulate hook for LilNounsToken.renounceOwnership
  useSimulateLilNounsTokenSafeTransferFrom, // React simulate hook for LilNounsToken.safeTransferFrom
  useSimulateLilNounsTokenSetApprovalForAll, // React simulate hook for LilNounsToken.setApprovalForAll
  useSimulateLilNounsTokenSetContractUriHash, // React simulate hook for LilNounsToken.setContractUriHash
  useSimulateLilNounsTokenSetDescriptor, // React simulate hook for LilNounsToken.setDescriptor
  useSimulateLilNounsTokenSetLilNoundersDao, // React simulate hook for LilNounsToken.setLilNoundersDao
  useSimulateLilNounsTokenSetMinter, // React simulate hook for LilNounsToken.setMinter
  useSimulateLilNounsTokenSetNounsDao, // React simulate hook for LilNounsToken.setNounsDao
  useSimulateLilNounsTokenSetSeeder, // React simulate hook for LilNounsToken.setSeeder
  useSimulateLilNounsTokenTransferFrom, // React simulate hook for LilNounsToken.transferFrom
  useSimulateLilNounsTokenTransferOwnership, // React simulate hook for LilNounsToken.transferOwnership
  useSimulateLilNounsTreasury, // React simulate hook for LilNounsTreasury
  useSimulateLilNounsTreasuryAcceptAdmin, // React simulate hook for LilNounsTreasury.acceptAdmin
  useSimulateLilNounsTreasuryCancelTransaction, // React simulate hook for LilNounsTreasury.cancelTransaction
  useSimulateLilNounsTreasuryExecuteTransaction, // React simulate hook for LilNounsTreasury.executeTransaction
  useSimulateLilNounsTreasuryQueueTransaction, // React simulate hook for LilNounsTreasury.queueTransaction
  useSimulateLilNounsTreasurySetDelay, // React simulate hook for LilNounsTreasury.setDelay
  useSimulateLilNounsTreasurySetPendingAdmin, // React simulate hook for LilNounsTreasury.setPendingAdmin
  useWatchLilNounsAuctionAuctionReservePriceUpdatedEvent, // React event hook for LilNounsAuction.auctionReservePriceUpdated
  useWatchLilNounsAuctionAuctionSettledEvent, // React event hook for LilNounsAuction.auctionSettled
  useWatchLilNounsAuctionAuctionUpdateIntervalUpdatedEvent, // React event hook for LilNounsAuction.auctionUpdateIntervalUpdated
  useWatchLilNounsAuctionDescriptorUpdatedEvent, // React event hook for LilNounsAuction.descriptorUpdated
  // Generated React hooks: event watchers
  useWatchLilNounsAuctionEvent, // React event hook for LilNounsAuction
  useWatchLilNounsAuctionInitializedEvent, // React event hook for LilNounsAuction.initialized
  useWatchLilNounsAuctionOwnershipTransferredEvent, // React event hook for LilNounsAuction.ownershipTransferred
  useWatchLilNounsAuctionPausedEvent, // React event hook for LilNounsAuction.paused
  useWatchLilNounsAuctionPoolSizeUpdatedEvent, // React event hook for LilNounsAuction.poolSizeUpdated
  useWatchLilNounsAuctionSeederUpdatedEvent, // React event hook for LilNounsAuction.seederUpdated
  useWatchLilNounsAuctionUnpausedEvent, // React event hook for LilNounsAuction.unpaused
  useWatchLilNounsAuctionUpgradedEvent, // React event hook for LilNounsAuction.upgraded
  useWatchLilNounsDataCandidateFeedbackSentEvent, // React event hook for LilNounsData.candidateFeedbackSent
  useWatchLilNounsDataCreateCandidateCostSetEvent, // React event hook for LilNounsData.createCandidateCostSet
  useWatchLilNounsDataEthWithdrawnEvent, // React event hook for LilNounsData.ethWithdrawn
  useWatchLilNounsDataEvent, // React event hook for LilNounsData
  useWatchLilNounsDataFeedbackSentEvent, // React event hook for LilNounsData.feedbackSent
  useWatchLilNounsDataFeeRecipientSetEvent, // React event hook for LilNounsData.feeRecipientSet
  useWatchLilNounsDataInitializedEvent, // React event hook for LilNounsData.initialized
  useWatchLilNounsDataOwnershipTransferredEvent, // React event hook for LilNounsData.ownershipTransferred
  useWatchLilNounsDataOwnershipTransferStartedEvent, // React event hook for LilNounsData.ownershipTransferStarted
  useWatchLilNounsDataProposalCandidateCanceledEvent, // React event hook for LilNounsData.proposalCandidateCanceled
  useWatchLilNounsDataProposalCandidateCreatedEvent, // React event hook for LilNounsData.proposalCandidateCreated
  useWatchLilNounsDataProposalCandidateUpdatedEvent, // React event hook for LilNounsData.proposalCandidateUpdated
  useWatchLilNounsDataUpdateCandidateCostSetEvent, // React event hook for LilNounsData.updateCandidateCostSet
  useWatchLilNounsDataUpgradedEvent, // React event hook for LilNounsData.upgraded
  useWatchLilNounsDescriptorArtUpdatedEvent, // React event hook for LilNounsDescriptor.artUpdated
  useWatchLilNounsDescriptorBaseUriUpdatedEvent, // React event hook for LilNounsDescriptor.baseUriUpdated
  useWatchLilNounsDescriptorDataUriToggledEvent, // React event hook for LilNounsDescriptor.dataUriToggled
  useWatchLilNounsDescriptorEvent, // React event hook for LilNounsDescriptor
  useWatchLilNounsDescriptorOwnershipTransferredEvent, // React event hook for LilNounsDescriptor.ownershipTransferred
  useWatchLilNounsDescriptorPartsLockedEvent, // React event hook for LilNounsDescriptor.partsLocked
  useWatchLilNounsDescriptorRendererUpdatedEvent, // React event hook for LilNounsDescriptor.rendererUpdated
  useWatchLilNounsEnsMapperAddrChangedEvent, // React event hook for LilNounsEnsMapper.addrChanged
  useWatchLilNounsEnsMapperEvent, // React event hook for LilNounsEnsMapper
  useWatchLilNounsEnsMapperInitializedEvent, // React event hook for LilNounsEnsMapper.initialized
  useWatchLilNounsEnsMapperNameChangedEvent, // React event hook for LilNounsEnsMapper.nameChanged
  useWatchLilNounsEnsMapperOwnershipTransferredEvent, // React event hook for LilNounsEnsMapper.ownershipTransferred
  useWatchLilNounsEnsMapperSubnameClaimedEvent, // React event hook for LilNounsEnsMapper.subnameClaimed
  useWatchLilNounsEnsMapperTextChangedEvent, // React event hook for LilNounsEnsMapper.textChanged
  useWatchLilNounsEnsMapperUpgradedEvent, // React event hook for LilNounsEnsMapper.upgraded
  useWatchLilNounsGovernorEvent, // React event hook for LilNounsGovernor
  useWatchLilNounsGovernorMaxQuorumVotesBpsSetEvent, // React event hook for LilNounsGovernor.maxQuorumVotesBpsSet
  useWatchLilNounsGovernorMinQuorumVotesBpsSetEvent, // React event hook for LilNounsGovernor.minQuorumVotesBpsSet
  useWatchLilNounsGovernorNewAdminEvent, // React event hook for LilNounsGovernor.newAdmin
  useWatchLilNounsGovernorNewImplementationEvent, // React event hook for LilNounsGovernor.newImplementation
  useWatchLilNounsGovernorNewPendingAdminEvent, // React event hook for LilNounsGovernor.newPendingAdmin
  useWatchLilNounsGovernorNewPendingVetoerEvent, // React event hook for LilNounsGovernor.newPendingVetoer
  useWatchLilNounsGovernorNewVetoerEvent, // React event hook for LilNounsGovernor.newVetoer
  useWatchLilNounsGovernorProposalCanceledEvent, // React event hook for LilNounsGovernor.proposalCanceled
  useWatchLilNounsGovernorProposalCreatedEvent, // React event hook for LilNounsGovernor.proposalCreated
  useWatchLilNounsGovernorProposalCreatedWithRequirementsEvent, // React event hook for LilNounsGovernor.proposalCreatedWithRequirements
  useWatchLilNounsGovernorProposalExecutedEvent, // React event hook for LilNounsGovernor.proposalExecuted
  useWatchLilNounsGovernorProposalQueuedEvent, // React event hook for LilNounsGovernor.proposalQueued
  useWatchLilNounsGovernorProposalThresholdBpsSetEvent, // React event hook for LilNounsGovernor.proposalThresholdBpsSet
  useWatchLilNounsGovernorProposalVetoedEvent, // React event hook for LilNounsGovernor.proposalVetoed
  useWatchLilNounsGovernorQuorumCoefficientSetEvent, // React event hook for LilNounsGovernor.quorumCoefficientSet
  useWatchLilNounsGovernorQuorumVotesBpsSetEvent, // React event hook for LilNounsGovernor.quorumVotesBpsSet
  useWatchLilNounsGovernorRefundableVoteEvent, // React event hook for LilNounsGovernor.refundableVote
  useWatchLilNounsGovernorVoteCastEvent, // React event hook for LilNounsGovernor.voteCast
  useWatchLilNounsGovernorVotingDelaySetEvent, // React event hook for LilNounsGovernor.votingDelaySet
  useWatchLilNounsGovernorVotingPeriodSetEvent, // React event hook for LilNounsGovernor.votingPeriodSet
  useWatchLilNounsGovernorWithdrawEvent, // React event hook for LilNounsGovernor.withdraw
  useWatchLilNounsTokenApprovalEvent, // React event hook for LilNounsToken.approval
  useWatchLilNounsTokenApprovalForAllEvent, // React event hook for LilNounsToken.approvalForAll
  useWatchLilNounsTokenDelegateChangedEvent, // React event hook for LilNounsToken.delegateChanged
  useWatchLilNounsTokenDelegateVotesChangedEvent, // React event hook for LilNounsToken.delegateVotesChanged
  useWatchLilNounsTokenDescriptorLockedEvent, // React event hook for LilNounsToken.descriptorLocked
  useWatchLilNounsTokenDescriptorUpdatedEvent, // React event hook for LilNounsToken.descriptorUpdated
  useWatchLilNounsTokenEvent, // React event hook for LilNounsToken
  useWatchLilNounsTokenLilNoundersDaoUpdatedEvent, // React event hook for LilNounsToken.lilNoundersDaoUpdated
  useWatchLilNounsTokenMinterLockedEvent, // React event hook for LilNounsToken.minterLocked
  useWatchLilNounsTokenMinterUpdatedEvent, // React event hook for LilNounsToken.minterUpdated
  useWatchLilNounsTokenNounBurnedEvent, // React event hook for LilNounsToken.nounBurned
  useWatchLilNounsTokenNounCreatedEvent, // React event hook for LilNounsToken.nounCreated
  useWatchLilNounsTokenNounsDaoUpdatedEvent, // React event hook for LilNounsToken.nounsDaoUpdated
  useWatchLilNounsTokenOwnershipTransferredEvent, // React event hook for LilNounsToken.ownershipTransferred
  useWatchLilNounsTokenSeederLockedEvent, // React event hook for LilNounsToken.seederLocked
  useWatchLilNounsTokenSeederUpdatedEvent, // React event hook for LilNounsToken.seederUpdated
  useWatchLilNounsTokenTransferEvent, // React event hook for LilNounsToken.transfer
  useWatchLilNounsTreasuryCancelTransactionEvent, // React event hook for LilNounsTreasury.cancelTransaction
  useWatchLilNounsTreasuryEvent, // React event hook for LilNounsTreasury
  useWatchLilNounsTreasuryExecuteTransactionEvent, // React event hook for LilNounsTreasury.executeTransaction
  useWatchLilNounsTreasuryNewAdminEvent, // React event hook for LilNounsTreasury.newAdmin
  useWatchLilNounsTreasuryNewDelayEvent, // React event hook for LilNounsTreasury.newDelay
  useWatchLilNounsTreasuryNewPendingAdminEvent, // React event hook for LilNounsTreasury.newPendingAdmin
  useWatchLilNounsTreasuryQueueTransactionEvent, // React event hook for LilNounsTreasury.queueTransaction
  // Generated React hooks: write helpers
  useWriteLilNounsAuction, // React write hook for LilNounsAuction
  useWriteLilNounsAuctionBuyNow, // React write hook for LilNounsAuction.buyNow
  useWriteLilNounsAuctionInitialize, // React write hook for LilNounsAuction.initialize
  useWriteLilNounsAuctionPause, // React write hook for LilNounsAuction.pause
  useWriteLilNounsAuctionRenounceOwnership, // React write hook for LilNounsAuction.renounceOwnership
  useWriteLilNounsAuctionSetNounsDescriptor, // React write hook for LilNounsAuction.setNounsDescriptor
  useWriteLilNounsAuctionSetNounsSeeder, // React write hook for LilNounsAuction.setNounsSeeder
  useWriteLilNounsAuctionSetPoolSize, // React write hook for LilNounsAuction.setPoolSize
  useWriteLilNounsAuctionSetReservePrice, // React write hook for LilNounsAuction.setReservePrice
  useWriteLilNounsAuctionSetUpdateInterval, // React write hook for LilNounsAuction.setUpdateInterval
  useWriteLilNounsAuctionTransferOwnership, // React write hook for LilNounsAuction.transferOwnership
  useWriteLilNounsAuctionUnpause, // React write hook for LilNounsAuction.unpause
  useWriteLilNounsAuctionUpgradeTo, // React write hook for LilNounsAuction.upgradeTo
  useWriteLilNounsAuctionUpgradeToAndCall, // React write hook for LilNounsAuction.upgradeToAndCall
  useWriteLilNounsData, // React write hook for LilNounsData
  useWriteLilNounsDataAcceptOwnership, // React write hook for LilNounsData.acceptOwnership
  useWriteLilNounsDataCancelProposalCandidate, // React write hook for LilNounsData.cancelProposalCandidate
  useWriteLilNounsDataCreateProposalCandidate, // React write hook for LilNounsData.createProposalCandidate
  useWriteLilNounsDataInitialize, // React write hook for LilNounsData.initialize
  useWriteLilNounsDataInitializeV2, // React write hook for LilNounsData.initializeV2
  useWriteLilNounsDataRenounceOwnership, // React write hook for LilNounsData.renounceOwnership
  useWriteLilNounsDataSendCandidateFeedback, // React write hook for LilNounsData.sendCandidateFeedback
  useWriteLilNounsDataSendFeedback, // React write hook for LilNounsData.sendFeedback
  useWriteLilNounsDataSetCreateCandidateCost, // React write hook for LilNounsData.setCreateCandidateCost
  useWriteLilNounsDataSetFeeRecipient, // React write hook for LilNounsData.setFeeRecipient
  useWriteLilNounsDataSetUpdateCandidateCost, // React write hook for LilNounsData.setUpdateCandidateCost
  useWriteLilNounsDataTransferOwnership, // React write hook for LilNounsData.transferOwnership
  useWriteLilNounsDataUpdateProposalCandidate, // React write hook for LilNounsData.updateProposalCandidate
  useWriteLilNounsDataUpgradeToAndCall, // React write hook for LilNounsData.upgradeToAndCall
  useWriteLilNounsDataWithdrawEth, // React write hook for LilNounsData.withdrawEth
  useWriteLilNounsDescriptor, // React write hook for LilNounsDescriptor
  useWriteLilNounsDescriptorAddAccessories, // React write hook for LilNounsDescriptor.addAccessories
  useWriteLilNounsDescriptorAddAccessoriesFromPointer, // React write hook for LilNounsDescriptor.addAccessoriesFromPointer
  useWriteLilNounsDescriptorAddBackground, // React write hook for LilNounsDescriptor.addBackground
  useWriteLilNounsDescriptorAddBodies, // React write hook for LilNounsDescriptor.addBodies
  useWriteLilNounsDescriptorAddBodiesFromPointer, // React write hook for LilNounsDescriptor.addBodiesFromPointer
  useWriteLilNounsDescriptorAddGlasses, // React write hook for LilNounsDescriptor.addGlasses
  useWriteLilNounsDescriptorAddGlassesFromPointer, // React write hook for LilNounsDescriptor.addGlassesFromPointer
  useWriteLilNounsDescriptorAddHeads, // React write hook for LilNounsDescriptor.addHeads
  useWriteLilNounsDescriptorAddHeadsFromPointer, // React write hook for LilNounsDescriptor.addHeadsFromPointer
  useWriteLilNounsDescriptorAddManyBackgrounds, // React write hook for LilNounsDescriptor.addManyBackgrounds
  useWriteLilNounsDescriptorLockParts, // React write hook for LilNounsDescriptor.lockParts
  useWriteLilNounsDescriptorRenounceOwnership, // React write hook for LilNounsDescriptor.renounceOwnership
  useWriteLilNounsDescriptorSetArt, // React write hook for LilNounsDescriptor.setArt
  useWriteLilNounsDescriptorSetArtDescriptor, // React write hook for LilNounsDescriptor.setArtDescriptor
  useWriteLilNounsDescriptorSetArtInflator, // React write hook for LilNounsDescriptor.setArtInflator
  useWriteLilNounsDescriptorSetBaseUri, // React write hook for LilNounsDescriptor.setBaseUri
  useWriteLilNounsDescriptorSetPalette, // React write hook for LilNounsDescriptor.setPalette
  useWriteLilNounsDescriptorSetPalettePointer, // React write hook for LilNounsDescriptor.setPalettePointer
  useWriteLilNounsDescriptorSetRenderer, // React write hook for LilNounsDescriptor.setRenderer
  useWriteLilNounsDescriptorToggleDataUriEnabled, // React write hook for LilNounsDescriptor.toggleDataUriEnabled
  useWriteLilNounsDescriptorTransferOwnership, // React write hook for LilNounsDescriptor.transferOwnership
  useWriteLilNounsEnsMapper, // React write hook for LilNounsEnsMapper
  useWriteLilNounsEnsMapperClaimSubname, // React write hook for LilNounsEnsMapper.claimSubname
  useWriteLilNounsEnsMapperEmitAddrEvents, // React write hook for LilNounsEnsMapper.emitAddrEvents
  useWriteLilNounsEnsMapperEmitTextEvents, // React write hook for LilNounsEnsMapper.emitTextEvents
  useWriteLilNounsEnsMapperInitialize, // React write hook for LilNounsEnsMapper.initialize
  useWriteLilNounsEnsMapperMigrateLegacySubname, // React write hook for LilNounsEnsMapper.migrateLegacySubname
  useWriteLilNounsEnsMapperReleaseLegacySubname, // React write hook for LilNounsEnsMapper.releaseLegacySubname
  useWriteLilNounsEnsMapperRelinquishSubname, // React write hook for LilNounsEnsMapper.relinquishSubname
  useWriteLilNounsEnsMapperRenounceOwnership, // React write hook for LilNounsEnsMapper.renounceOwnership
  useWriteLilNounsEnsMapperRestoreResolver, // React write hook for LilNounsEnsMapper.restoreResolver
  useWriteLilNounsEnsMapperSetText, // React write hook for LilNounsEnsMapper.setText
  useWriteLilNounsEnsMapperTransferOwnership, // React write hook for LilNounsEnsMapper.transferOwnership
  useWriteLilNounsEnsMapperUpgradeToAndCall, // React write hook for LilNounsEnsMapper.upgradeToAndCall
  useWriteLilNounsGovernor, // React write hook for LilNounsGovernor
  useWriteLilNounsGovernorAcceptAdmin, // React write hook for LilNounsGovernor.acceptAdmin
  useWriteLilNounsGovernorAcceptVetoer, // React write hook for LilNounsGovernor.acceptVetoer
  useWriteLilNounsGovernorBurnVetoPower, // React write hook for LilNounsGovernor.burnVetoPower
  useWriteLilNounsGovernorCancel, // React write hook for LilNounsGovernor.cancel
  useWriteLilNounsGovernorCastRefundableVote, // React write hook for LilNounsGovernor.castRefundableVote
  useWriteLilNounsGovernorCastRefundableVoteWithReason, // React write hook for LilNounsGovernor.castRefundableVoteWithReason
  useWriteLilNounsGovernorCastVote, // React write hook for LilNounsGovernor.castVote
  useWriteLilNounsGovernorCastVoteBySig, // React write hook for LilNounsGovernor.castVoteBySig
  useWriteLilNounsGovernorCastVoteWithReason, // React write hook for LilNounsGovernor.castVoteWithReason
  useWriteLilNounsGovernorExecute, // React write hook for LilNounsGovernor.execute
  useWriteLilNounsGovernorInitialize, // React write hook for LilNounsGovernor.initialize
  useWriteLilNounsGovernorPropose, // React write hook for LilNounsGovernor.propose
  useWriteLilNounsGovernorQueue, // React write hook for LilNounsGovernor.queue
  useWriteLilNounsGovernorSetDynamicQuorumParams, // React write hook for LilNounsGovernor.setDynamicQuorumParams
  useWriteLilNounsGovernorSetMaxQuorumVotesBps, // React write hook for LilNounsGovernor.setMaxQuorumVotesBps
  useWriteLilNounsGovernorSetMinQuorumVotesBps, // React write hook for LilNounsGovernor.setMinQuorumVotesBps
  useWriteLilNounsGovernorSetPendingAdmin, // React write hook for LilNounsGovernor.setPendingAdmin
  useWriteLilNounsGovernorSetPendingVetoer, // React write hook for LilNounsGovernor.setPendingVetoer
  useWriteLilNounsGovernorSetProposalThresholdBps, // React write hook for LilNounsGovernor.setProposalThresholdBps
  useWriteLilNounsGovernorSetQuorumCoefficient, // React write hook for LilNounsGovernor.setQuorumCoefficient
  useWriteLilNounsGovernorSetVotingDelay, // React write hook for LilNounsGovernor.setVotingDelay
  useWriteLilNounsGovernorSetVotingPeriod, // React write hook for LilNounsGovernor.setVotingPeriod
  useWriteLilNounsGovernorVeto, // React write hook for LilNounsGovernor.veto
  useWriteLilNounsGovernorWithdraw, // React write hook for LilNounsGovernor.withdraw
  useWriteLilNounsToken, // React write hook for LilNounsToken
  useWriteLilNounsTokenApprove, // React write hook for LilNounsToken.approve
  useWriteLilNounsTokenBurn, // React write hook for LilNounsToken.burn
  useWriteLilNounsTokenDelegate, // React write hook for LilNounsToken.delegate
  useWriteLilNounsTokenDelegateBySig, // React write hook for LilNounsToken.delegateBySig
  useWriteLilNounsTokenLockDescriptor, // React write hook for LilNounsToken.lockDescriptor
  useWriteLilNounsTokenLockMinter, // React write hook for LilNounsToken.lockMinter
  useWriteLilNounsTokenLockSeeder, // React write hook for LilNounsToken.lockSeeder
  useWriteLilNounsTokenMint, // React write hook for LilNounsToken.mint
  useWriteLilNounsTokenRenounceOwnership, // React write hook for LilNounsToken.renounceOwnership
  useWriteLilNounsTokenSafeTransferFrom, // React write hook for LilNounsToken.safeTransferFrom
  useWriteLilNounsTokenSetApprovalForAll, // React write hook for LilNounsToken.setApprovalForAll
  useWriteLilNounsTokenSetContractUriHash, // React write hook for LilNounsToken.setContractUriHash
  useWriteLilNounsTokenSetDescriptor, // React write hook for LilNounsToken.setDescriptor
  useWriteLilNounsTokenSetLilNoundersDao, // React write hook for LilNounsToken.setLilNoundersDao
  useWriteLilNounsTokenSetMinter, // React write hook for LilNounsToken.setMinter
  useWriteLilNounsTokenSetNounsDao, // React write hook for LilNounsToken.setNounsDao
  useWriteLilNounsTokenSetSeeder, // React write hook for LilNounsToken.setSeeder
  useWriteLilNounsTokenTransferFrom, // React write hook for LilNounsToken.transferFrom
  useWriteLilNounsTokenTransferOwnership, // React write hook for LilNounsToken.transferOwnership
  useWriteLilNounsTreasury, // React write hook for LilNounsTreasury
  useWriteLilNounsTreasuryAcceptAdmin, // React write hook for LilNounsTreasury.acceptAdmin
  useWriteLilNounsTreasuryCancelTransaction, // React write hook for LilNounsTreasury.cancelTransaction
  useWriteLilNounsTreasuryExecuteTransaction, // React write hook for LilNounsTreasury.executeTransaction
  useWriteLilNounsTreasuryQueueTransaction, // React write hook for LilNounsTreasury.queueTransaction
  useWriteLilNounsTreasurySetDelay, // React write hook for LilNounsTreasury.setDelay
  useWriteLilNounsTreasurySetPendingAdmin, // React write hook for LilNounsTreasury.setPendingAdmin
} from "./react.gen";
